# Lesson 1: Advanced RAG Pipeline

In [1]:
import utils

print(f"Gemini API key loaded: {bool(utils.get_google_api_key())}")

Gemini API key loaded: True

In [2]:
from llama_index.core import SimpleDirectoryReader

documents = SimpleDirectoryReader(
    input_files=["./eBook-How-to-Build-a-Career-in-AI.pdf"]
).load_data()

In [3]:
print(type(documents), "\n")
print(len(documents), "\n")
print(type(documents[0]))
print(documents[0])

<class 'list'>

41

<class 'llama_index.core.schema.Document'>
Doc ID: ec028276-efa1-442b-8f88-70ff9150ae09
Text: PAGE 1 Founder, DeepLearning.AI Collected Insights from Andrew
Ng How to  Build Your Career in AI A Simple Guide

## Basic RAG pipeline

In [4]:
from llama_index.core import Document

document = Document(text="\n\n".join([doc.text for doc in documents]))

In [5]:
from llama_index.core import Settings, VectorStoreIndex
from llama_index.llms.google_genai import GoogleGenAI
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

llm = GoogleGenAI(
    model="gemma-4-31b-it",
    api_key=utils.get_google_api_key(),
    temperature=0.1,
)
Settings.llm = llm
Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
index = VectorStoreIndex.from_documents([document])

2026-07-20 21:45:00,592 - INFO - HTTP Request: GET https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it "HTTP/1.1 200 OK"
2026-07-20 21:45:01,085 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-07-20 21:45:01,087 - WARNING - Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-07-20 21:45:01,232 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 21:45:01,532 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:45:01,629 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 21:45:01,631 - INFO - Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-07-20 21:45:01,907 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:45:01,930 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 21:45:02,218 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:45:02,247 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-07-20 21:45:02,537 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:45:02,565 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 21:45:02,881 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:45:02,907 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-07-20 21:45:03,195 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:45:03,507 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:45:03,529 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

2026-07-20 21:45:04,055 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:45:04,340 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:45:04,650 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:45:04,959 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:45:05,284 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:45:05,310 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 21:45:05,590 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:45:05,620 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 21:45:06,002 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:45:06,028 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 21:45:06,413 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:45:06,442 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 21:45:06,727 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-20 21:45:07,023 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-20 21:45:07,398 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:45:07,424 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-07-20 21:45:07,747 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-07-20 21:45:08,169 - INFO - Loaded 1 prompt with these keys: ['query']

In [6]:
query_engine = index.as_query_engine()

In [7]:
response = query_engine.query(
    "What are steps to take when finding projects to build your experience?"
)
print(str(response))

2026-07-20 21:45:11,453 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 21:45:38,309 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"

To find projects to build experience, you can generate ideas through the following steps:

*   **Join existing projects:** Ask to join a project if you find someone else who has an idea.
*   **Engage in learning and networking:** Spend time reading, taking courses, and talking with domain experts.
*   **Focus on application areas:** Explore machine learning possibilities within application areas that your school or company cares about, as this can lead to unique work.
*   **Develop a side hustle:** Start a fun hobby project that can strengthen bonds with collaborators and stir creativity.

Once you have project ideas, use the following checklist to decide which one to pursue:
*   **Technical growth:** Determine if the project is challenging enough to stretch your skills without being so difficult that success is unlikely.
*   **Collaboration:** Consider if you have good teammates or people available to discuss the project with.
*   **Stepping stone potential:** Evaluate if the project's business impact or technical complexity could lead to larger projects.

Additionally, avoid analysis paralysis. Depending on the situation, you can use a "ready, fire, aim" approach to accelerate progress, or a "ready, aim, fire" approach when the cost of execution is high and a study is needed to determine the project's value.

## Evaluation setup (LlamaIndex RAG triad)

In [9]:
eval_questions = []
with open('eval_questions.txt', 'r') as file:
    for line in file:
        # Remove newline character and convert to integer
        item = line.strip()
        print(item)
        eval_questions.append(item)

What are the keys to building a career in AI?
How can teamwork contribute to success in AI?
What is the importance of networking in AI?
What are some good habits to develop for a successful career?
How can altruism be beneficial in building a career?
What is imposter syndrome and how does it relate to AI?
Who are some accomplished individuals who have experienced imposter syndrome?
What is the first step to becoming good at AI?
What are some common challenges in AI?
Is it normal to find parts of AI challenging?

In [10]:
# You can try your own question:
new_question = "What is the right AI job for me?"
eval_questions.append(new_question)

In [11]:
print(eval_questions)

['What are the keys to building a career in AI?', 'How can teamwork contribute to success in AI?', 'What is the importance of networking in AI?', 'What are some good habits to develop for a successful career?', 'How can altruism be beneficial in building a career?', 'What is imposter syndrome and how does it relate to AI?', 'Who are some accomplished individuals who have experienced imposter syndrome?', 'What is the first step to becoming good at AI?', 'What are some common challenges in AI?', 'Is it normal to find parts of AI challenging?', 'What is the right AI job for me?']

In [12]:
from utils import get_eval_llm, evaluate_query_engine, summarize_eval_df

eval_llm = get_eval_llm()

2026-07-20 21:45:47,945 - INFO - HTTP Request: GET https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it "HTTP/1.1 200 OK"

Evaluation helpers live in `utils.py` (re-exported from `week_4/helper.py`):

- `get_eval_llm()` — Gemini judge (`temperature=0`)
- `evaluate_query_engine(...)` — Answer Relevancy, Context Relevancy, Groundedness
- `summarize_eval_df(...)` — mean scores (replaces a leaderboard)

In [27]:
# Evaluate the basic query engine on the RAG triad
records_basic = evaluate_query_engine(
    query_engine,
    eval_questions,
    app_id="basic_query_engine",
    llm=eval_llm,
)
records_basic.head()

2026-07-20 22:15:25,186 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:15:44,432 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:15:44,444 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:16:07,365 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:16:31,430 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:16:45,555 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:16:58,085 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:16:58,091 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:17:10,055 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:17:33,752 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:17:51,370 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:18:01,371 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:18:01,379 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:18:07,435 - WARNING - Retrying llama_index.llms.google_genai.base.GoogleGenAI._achat in 1 seconds as it raised ServerError: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}.
2026-07-20 22:18:08,438 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:18:39,831 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:19:06,564 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:19:16,440 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:19:25,102 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:19:25,108 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:19:54,916 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:20:23,485 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:20:34,667 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:20:41,280 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:20:41,286 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:21:14,017 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:21:40,709 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:21:49,391 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:22:01,236 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:22:01,242 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:22:13,771 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:22:32,450 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:22:43,783 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:22:53,927 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:22:53,939 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:23:05,486 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:23:25,791 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:23:34,006 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:23:40,700 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:23:40,710 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:23:53,537 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:24:15,294 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:24:24,013 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:24:44,593 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:24:44,600 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:24:57,834 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:25:24,687 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:25:48,460 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:25:59,530 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:25:59,532 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:26:11,944 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:26:34,718 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:26:46,409 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:27:03,326 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:27:03,336 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:27:19,382 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:27:55,248 - INFO - AFC is enabled with max remote calls: 10.

,app_id,question,answer,answer_relevancy,context_relevancy,groundedness
0,basic_query_engine,What are the keys to building a career in AI?,The keys to building a career in AI include th...,1.0,1.00,1.0
1,basic_query_engine,How can teamwork contribute to success in AI?,"When tackling large projects, working in teams...",1.0,1.00,1.0
2,basic_query_engine,What is the importance of networking in AI?,A strong professional network is important bec...,0.0,1.00,1.0
3,basic_query_engine,What are some good habits to develop for a suc...,Successful people often develop good habits in...,0.5,1.00,1.0
4,basic_query_engine,How can altruism be beneficial in building a c...,People who aim to lift others during every ste...,0.5,0.75,1.0

In [28]:
summarize_eval_df(records_basic)

               app_id  answer_relevancy  context_relevancy  groundedness
0  basic_query_engine          0.818182           0.897727           1.0

In [16]:
records_basic[
    ["question", "answer_relevancy", "context_relevancy", "groundedness"]
]

,question,answer_relevancy,context_relevancy,groundedness
0,What are the keys to building a career in AI?,1.0,1.0,1.0
1,How can teamwork contribute to success in AI?,1.0,1.0,1.0
2,What is the importance of networking in AI?,0.0,1.0,1.0
3,What are some good habits to develop for a suc...,0.5,1.0,1.0

## Advanced RAG pipeline

### 1. Sentence Window retrieval

In [18]:
from llama_index.llms.google_genai import GoogleGenAI

llm = GoogleGenAI(
    model="gemma-4-31b-it",
    api_key=utils.get_google_api_key(),
    temperature=0.1,
)

2026-07-20 21:56:06,475 - INFO - HTTP Request: GET https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it "HTTP/1.1 200 OK"

In [19]:
from utils import build_sentence_window_index

sentence_index = build_sentence_window_index(
    document,
    llm,
    embed_model="local:BAAI/bge-small-en-v1.5",
    save_dir="sentence_index"
)

2026-07-20 21:56:08,340 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:08,368 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 21:56:08,678 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:08,701 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 21:56:08,705 - INFO - Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-07-20 21:56:09,064 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:09,088 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 21:56:09,389 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:09,412 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-07-20 21:56:09,779 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:09,802 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 21:56:10,107 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:10,131 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-07-20 21:56:10,445 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:56:10,790 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:10,814 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

2026-07-20 21:56:11,223 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:56:11,528 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:56:11,836 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:56:12,214 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:56:12,526 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:12,549 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 21:56:12,857 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:12,879 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 21:56:13,241 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:13,264 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 21:56:13,565 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:13,597 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 21:56:13,975 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-20 21:56:14,321 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-20 21:56:14,701 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:14,728 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-07-20 21:56:15,039 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-07-20 21:56:15,521 - INFO - Loaded 1 prompt with these keys: ['query']

In [20]:
from utils import get_sentence_window_query_engine

sentence_window_engine = get_sentence_window_query_engine(sentence_index)

2026-07-20 21:56:16,165 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/modules.json "HTTP/1.1 404 Not Found"
2026-07-20 21:56:16,168 - INFO - No modules.json found for BAAI/bge-reranker-base, initializing a new CrossEncoder model.
2026-07-20 21:56:16,529 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"
2026-07-20 21:56:16,912 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:16,934 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 21:56:17,041 - INFO - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"

config.json:   0%|          | 0.00/799 [00:00<?, ?B/s]

2026-07-20 21:56:17,365 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:56:17,732 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:56:17,754 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 21:56:18,083 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/model.safetensors "HTTP/1.1 302 Found"

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.11GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

2026-07-20 21:57:30,450 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:57:30,759 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:57:31,112 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:57:31,420 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 21:57:31,798 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:57:31,887 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 21:57:31,907 - INFO - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

2026-07-20 21:57:32,232 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:57:32,256 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 21:57:32,576 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:57:32,597 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 21:57:33,027 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:57:33,052 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 21:57:33,361 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-20 21:57:33,674 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-20 21:57:33,988 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/sentencepiece.bpe.model "HTTP/1.1 302 Found"

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

2026-07-20 21:57:37,130 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer.json "HTTP/1.1 302 Found"

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

2026-07-20 21:57:40,835 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
2026-07-20 21:57:41,216 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/special_tokens_map.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 21:57:41,322 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/special_tokens_map.json "HTTP/1.1 200 OK"
2026-07-20 21:57:41,347 - INFO - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/special_tokens_map.json "HTTP/1.1 200 OK"

special_tokens_map.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

2026-07-20 21:57:41,846 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
2026-07-20 21:57:43,159 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"

In [21]:
window_response = sentence_window_engine.query(
    "how do I get started on a personal project in AI?"
)
print(str(window_response))

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 21:57:44,926 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 21:57:44,927 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 21:57:44,927 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 21:57:44,928 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 21:58:03,359 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"

To get started on a personal project in AI, follow these guidelines:

*   **Start small:** Do not worry about beginning with very simple projects. For example, training a neural network to mimic the sin(x) function may not be highly useful, but it serves as a great learning experience that enables you to move on to larger projects.
*   **Focus on progression:** Aim to build a portfolio that demonstrates your skill progression over time, moving from simple undertakings to more complex ones.
*   **Communicate the value:** Clearly explain your thinking and the value of what you hope to build. This helps bring managers, mentors, and colleagues onboard and allows them to identify flaws in your reasoning.
*   **Build a foundation:** Ensure you have first focused on learning foundational technical skills before moving into the project phase.
*   **Manage expectations:** Be aware that AI projects are highly iterative, which can make it challenging to set expectations or estimate the project's return on investment and timeline.

In [22]:
records_sentence = evaluate_query_engine(
    sentence_window_engine,
    eval_questions,
    app_id="sentence_window",
    llm=eval_llm,
)
records_sentence.head()

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:00:24,483 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:00:24,484 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-889' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-890' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/linecache.py:52: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def checkcache(filename=None):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:00:24,488 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-890' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:00:24,483 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:00:24,489 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:00:51,172 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:00:51,179 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:01:13,184 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:01:35,220 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:01:51,321 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:01:51,322 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:01:51,323 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:01:51,323 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:01:51,324 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:02:03,391 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:02:03,401 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-940' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-942' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py:1354: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def _make_invoke_excepthook():
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:02:03,402 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-942' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:02:03,402 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-943' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-944' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:02:03,403 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-944' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:02:03,410 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:02:18,181 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:02:42,395 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:02:59,729 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:02:59,729 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:02:59,730 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:02:59,730 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:02:59,730 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:03:08,292 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:03:08,298 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:03:08,300 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-989' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-991' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:03:08,301 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-991' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:03:08,301 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-992' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-993' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:03:08,301 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-993' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:03:26,960 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:04:11,544 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:04:26,179 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:04:26,179 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:04:26,180 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:04:26,180 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:04:26,181 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:04:26,381 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1038' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1040' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/iostream.py:803: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  self._buffers = defaultdict(StringIO)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:04:26,384 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1040' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:04:26,384 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1041' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1042' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:04:26,385 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1042' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:04:26,385 - ERROR - Exception in callback functools.partial(<bound method OutStream._flush of <ipykernel.iostream.OutStream object at 0x1045d9b10>>)
Traceback (most recent call last):
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/iostream.py", line 713, in _flush
    for parent, data in self._flush_buffers():
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/iostream.py", line 795, in _flush_buffers
    data = buffer.getvalue()
           ^^^^^^^^^^^^^^^^^
ValueError: I/O operation on closed file
ERROR:tornado.application:Exception in callback functools.partial(<bound method OutStream._flush of <ipykernel.iostream.OutStream object at 0x1045d9b10>>)
Traceback (most recent call last):
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/iostream.py", line 713, in _flush
    for parent, data in self._flush_buffers():
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/iostream.py", line 795, in _flush_buffers
    data = buffer.getvalue()
           ^^^^^^^^^^^^^^^^^
ValueError: I/O operation on closed file
2026-07-20 22:04:37,088 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:04:37,093 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:05:06,486 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:05:30,593 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:05:44,270 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:05:44,271 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:05:44,271 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:05:44,272 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:05:44,273 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:05:51,433 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:05:51,441 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:05:51,443 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1087' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1089' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/pydantic/main.py:1250: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  yield from [(k, v) for (k, v) in self.__dict__.items() if not k.startswith('_')]
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:05:51,450 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1089' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:05:51,450 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1090' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1091' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:05:51,451 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1091' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:06:24,281 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:06:49,811 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:06:58,143 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:06:58,144 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:06:58,144 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:06:58,145 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:06:58,146 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:07:10,078 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:07:10,084 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:07:21,993 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-995' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:07:21,995 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-996' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1037' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py:2539: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  pass
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:07:22,004 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-994' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-995' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:07:22,005 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1037' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:07:22,006 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1044' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:07:22,006 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1045' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1086' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:07:22,007 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1043' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1044' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:07:22,008 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1086' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:07:22,008 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1093' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:07:22,009 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1094' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1135' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:07:22,009 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1092' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1093' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:07:22,010 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1135' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:07:22,010 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1136' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1138' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:07:22,012 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1138' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:07:22,012 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1139' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1140' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:07:22,012 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1140' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:07:22,032 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:07:40,378 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:07:52,804 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:07:52,805 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:07:52,807 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:07:52,808 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:07:52,809 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:08:04,634 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:08:04,640 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:08:04,644 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1185' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1187' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py:277: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def __init__(self, lock=None):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:08:04,644 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1187' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:08:04,645 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1188' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1189' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:08:04,645 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1189' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:08:16,463 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:08:32,586 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:08:42,963 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:08:42,964 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:08:42,964 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:08:42,965 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:08:42,965 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:08:43,166 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1234' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1236' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:08:43,166 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1236' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:08:43,167 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1237' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1238' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:08:43,167 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1238' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:08:43,167 - ERROR - Exception in callback functools.partial(<bound method OutStream._flush of <ipykernel.iostream.OutStream object at 0x1045d9b10>>)
Traceback (most recent call last):
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/iostream.py", line 713, in _flush
    for parent, data in self._flush_buffers():
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/iostream.py", line 795, in _flush_buffers
    data = buffer.getvalue()
           ^^^^^^^^^^^^^^^^^
ValueError: I/O operation on closed file
ERROR:tornado.application:Exception in callback functools.partial(<bound method OutStream._flush of <ipykernel.iostream.OutStream object at 0x1045d9b10>>)
Traceback (most recent call last):
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/iostream.py", line 713, in _flush
    for parent, data in self._flush_buffers():
  File "/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/iostream.py", line 795, in _flush_buffers
    data = buffer.getvalue()
           ^^^^^^^^^^^^^^^^^
ValueError: I/O operation on closed file
2026-07-20 22:08:57,662 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:08:57,679 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:09:09,738 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:09:27,081 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:09:46,510 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:09:46,511 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:09:46,512 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:09:46,513 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:09:46,514 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:10:02,231 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:10:02,261 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:10:02,268 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1283' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1285' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:10:02,269 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1285' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:10:02,269 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1286' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1287' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:10:02,269 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1287' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:10:20,578 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:10:52,098 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:10:52,103 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1191' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:10:52,103 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1192' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1233' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/futures.py:119: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def get_loop(self):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:10:52,104 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1190' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1191' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:10:52,105 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1233' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:10:52,106 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1240' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:10:52,107 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1241' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1282' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:10:52,108 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1239' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1240' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:10:52,109 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1282' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:11:07,606 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:11:07,607 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:11:07,608 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:11:07,608 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:11:07,609 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:11:07,610 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1332' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1334' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:11:07,611 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1334' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:11:07,611 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1335' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1336' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:11:07,611 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1336' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:11:18,065 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:11:18,070 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:11:29,213 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:11:47,720 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:11:57,658 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:11:57,659 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:11:57,659 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:11:57,660 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:11:57,660 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:12:15,935 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:12:15,940 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:12:15,943 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1381' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1383' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/_weakrefset.py:88: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  self.data.add(ref(item, self._remove))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:12:15,949 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1383' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:12:15,951 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1384' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-1385' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:12:15,951 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1385' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:12:33,589 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:13:28,647 - INFO - AFC is enabled with max remote calls: 10.

,app_id,question,answer,answer_relevancy,context_relevancy,groundedness
0,sentence_window,What are the keys to building a career in AI?,The keys to building a career in AI include th...,1.0,1.000,1.0
1,sentence_window,How can teamwork contribute to success in AI?,Teamwork contributes to success in AI because ...,1.0,1.000,1.0
2,sentence_window,What is the importance of networking in AI?,Having a strong professional network is import...,0.0,1.000,1.0
3,sentence_window,What are some good habits to develop for a suc...,Successful people often develop good habits in...,0.5,1.000,1.0
4,sentence_window,How can altruism be beneficial in building a c...,People who aim to lift others during every ste...,0.5,0.625,1.0

In [23]:
for _, row in records_sentence.iterrows():
    print(row["question"])
    print(row["answer"][:300], "...")
    print(
        "AR/CR/G:",
        row["answer_relevancy"],
        row["context_relevancy"],
        row["groundedness"],
    )
    print("---")

What are the keys to building a career in AI?
The keys to building a career in AI include the following:

*   **Teamwork:** Interpersonal and communication skills are critical because large projects are more successfully completed by working in teams rather than individually.
*   **Networking:** A strong professional network can provide necessa ...
AR/CR/G: 1.0 1.0 1.0
---
How can teamwork contribute to success in AI?
Teamwork contributes to success in AI because large projects are handled more successfully in teams than individually. It requires the critical ability to collaborate with, influence, and be influenced by others. Additionally, on larger AI projects, the ability to lead and steer the project by apply ...
AR/CR/G: 1.0 1.0 1.0
---
What is the importance of networking in AI?
Having a strong professional network is important because it can help propel you forward during times when you need advice or help. Rather than traditional networking, focusing on building up the communities you are a part of can be a helpful alternative that also allows you to meet more people and  ...
AR/CR/G: 0.0 1.0 1.0
---
What are some good habits to develop for a successful career?
Successful people often develop good habits in the following areas to help them move forward while staying healthy:
* Eating
* Exercise
* Sleep
* Personal relationships
* Work
* Learning
* Self-care ...
AR/CR/G: 0.5 1.0 1.0
---
How can altruism be beneficial in building a career?
People who aim to lift others during every step of their own journey often achieve better outcomes for themselves. ...
AR/CR/G: 0.5 0.625 1.0
---
What is imposter syndrome and how does it relate to AI?
Imposter syndrome is a feeling where an individual, regardless of their success in a field, wonders if they are a fraud and whether they truly belong in their community. In the AI community, this experience occurs even among accomplished people, partly because AI is technically complex and filled wi ...
AR/CR/G: 1.0 1.0 1.0
---
Who are some accomplished individuals who have experienced imposter syndrome?
Accomplished individuals who have spoken publicly about experiencing imposter syndrome include actor Tom Hanks, U.S. first lady Michelle Obama, Atlassian co-CEO Mike Cannon-Brookes, and former Facebook COO Sheryl Sandberg. ...
AR/CR/G: 1.0 1.0 1.0
---
What is the first step to becoming good at AI?
The first step to building a career in AI is learning foundational technical skills. This includes:

*   **Foundational machine learning skills:** Understanding core concepts such as error analysis, optimization algorithms, regularization, cost functions, and bias/variance, as well as models like an ...
AR/CR/G: 1.0 1.0 1.0
---
What are some common challenges in AI?
Common challenges in AI include:

*   **Technical Complexity:** AI is technically complex, with specific hurdles such as understanding the math behind linear regression, dealing with strange performance in logistic regression, finding bugs in basic neural network implementations, tuning neural netwo ...
AR/CR/G: 1.0 0.375 1.0
---
Is it normal to find parts of AI challenging?
Yes, it is normal to find parts of AI challenging because the field is technically complex. Even those who have published seminal AI papers have struggled with similar technical challenges at some point. ...
AR/CR/G: 1.0 1.0 1.0
---
What is the right AI job for me?
To find the right AI job, you should take an incremental approach by identifying possible roles and conducting a handful of informational interviews. It is important to consider not only the projects you will work on but also the teammates you will work with, as colleagues are at least equally impor ...
AR/CR/G: 1.0 0.875 1.0
---

In [24]:
summarize_eval_df(records_sentence)

            app_id  answer_relevancy  context_relevancy  groundedness
0  sentence_window          0.818182           0.897727           1.0

In [25]:
print("Sentence-window evaluation complete.")

Sentence-window evaluation complete.

### 2. Auto-merging retrieval

In [29]:
from utils import build_automerging_index

automerging_index = build_automerging_index(
    documents,
    llm,
    embed_model="local:BAAI/bge-small-en-v1.5",
    save_dir="merging_index"
)

2026-07-20 22:28:27,190 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:27,224 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 22:28:27,702 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:27,733 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 22:28:27,736 - INFO - Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-07-20 22:28:28,072 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:28,099 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 22:28:28,443 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:28,475 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-07-20 22:28:28,862 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:28,977 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 22:28:29,376 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:29,505 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-07-20 22:28:29,807 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:28:30,083 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:30,165 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

2026-07-20 22:28:30,543 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:28:30,827 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:28:31,113 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:28:31,397 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:28:31,667 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:31,691 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:28:31,999 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:32,021 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 22:28:32,306 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:32,327 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 22:28:32,629 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:32,652 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:28:32,926 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-20 22:28:33,211 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-20 22:28:33,580 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:33,603 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-07-20 22:28:33,957 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-07-20 22:28:34,252 - INFO - Loaded 1 prompt with these keys: ['query']
2026-07-20 22:28:34,370 - INFO - Loading all indices.

In [30]:
from utils import get_automerging_query_engine

automerging_query_engine = get_automerging_query_engine(
    automerging_index,
)

2026-07-20 22:28:34,655 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/modules.json "HTTP/1.1 404 Not Found"
2026-07-20 22:28:34,660 - INFO - No modules.json found for BAAI/bge-reranker-base, initializing a new CrossEncoder model.
2026-07-20 22:28:34,999 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"
2026-07-20 22:28:35,274 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:35,294 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:28:35,581 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:28:35,856 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:35,879 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

2026-07-20 22:28:36,300 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:28:36,576 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:28:36,852 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:28:37,139 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:28:37,429 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:37,455 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:28:37,873 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:37,897 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:28:38,176 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:38,201 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:28:38,491 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:28:38,514 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:28:38,795 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-20 22:28:39,079 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-20 22:28:39,840 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-588' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-615' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/transformers/tokenization_utils_tokenizers.py:181: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  vocab = [tuple(item) for item in vocab]
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:28:39,845 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-615' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:28:39,845 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-946' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:28:39,846 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-947' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-988' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:28:39,846 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-945' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-946' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:28:39,846 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-988' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:28:39,847 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1142' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:28:39,847 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1143' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1184' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:28:39,848 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1141' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1142' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:28:39,848 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1184' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:28:39,848 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1289' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:28:39,848 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1290' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1331' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:28:39,848 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1288' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1289' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:28:39,848 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1331' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:28:40,538 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"

In [31]:
auto_merging_response = automerging_query_engine.query(
    "How do I build a portfolio of AI projects?"
)
print(str(auto_merging_response))

2026-07-20 22:28:41,612 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f9d65dc7-7220-4588-b101-310ab01881f1.
> Parent node text: PAGE 21
Building a Portfolio of
Projects that Shows
Skill Progression
CHAPTER 6
PROJECTS

2026-07-20 22:28:41,613 - INFO - > Merging 1 nodes into parent node.
> Parent node id: eec9cee2-4831-40e3-9d0d-668b6611e162.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

2026-07-20 22:28:41,613 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 62a25e23-e33b-4395-8b03-7c53002c2103.
> Parent node text: PAGE 14
Scoping Successful
AI Projects
CHAPTER 4
PROJECTS

2026-07-20 22:28:41,613 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 5fbe1957-b9ad-4d60-ba0b-4380c032eb16.
> Parent node text: PAGE 21
Building a Portfolio of
Projects that Shows
Skill Progression
CHAPTER 6
PROJECTS

2026-07-20 22:28:41,613 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 38852a70-a7d4-4243-8924-34fdc5e74fd8.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

2026-07-20 22:28:41,614 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7fe0bbb8-e175-431d-9fa8-16a0b5e50e1c.
> Parent node text: PAGE 14
Scoping Successful
AI Projects
CHAPTER 4
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: f9d65dc7-7220-4588-b101-310ab01881f1.
> Parent node text: PAGE 21
Building a Portfolio of
Projects that Shows
Skill Progression
CHAPTER 6
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: eec9cee2-4831-40e3-9d0d-668b6611e162.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 62a25e23-e33b-4395-8b03-7c53002c2103.
> Parent node text: PAGE 14
Scoping Successful
AI Projects
CHAPTER 4
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 5fbe1957-b9ad-4d60-ba0b-4380c032eb16.
> Parent node text: PAGE 21
Building a Portfolio of
Projects that Shows
Skill Progression
CHAPTER 6
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 38852a70-a7d4-4243-8924-34fdc5e74fd8.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 7fe0bbb8-e175-431d-9fa8-16a0b5e50e1c.
> Parent node text: PAGE 14
Scoping Successful
AI Projects
CHAPTER 4
PROJECTS

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:28:41,961 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:28:41,962 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:28:41,963 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:28:41,963 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:28:52,135 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"

To build a portfolio of projects, focus on creating a collection that demonstrates progress over time, moving from simple to complex undertakings. Additionally, it is important to develop the ability to identify ideas that are worth working on and maintain strong communication skills to explain your thinking, which allows others to see the value in your work and trust you with resources for larger projects.

In [32]:
records_automerging = evaluate_query_engine(
    automerging_query_engine,
    eval_questions,
    app_id="automerging",
    llm=eval_llm,
)
records_automerging.head()

2026-07-20 22:28:58,553 - INFO - > Merging 2 nodes into parent node.
> Parent node id: 5f3f17ca-e56a-4f3b-9f3d-29d30b50cec5.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 22:28:58,553 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 62fbb4b9-df65-46b4-b2d1-c4178b693bd6.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 2 nodes into parent node.
> Parent node id: 5f3f17ca-e56a-4f3b-9f3d-29d30b50cec5.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: 62fbb4b9-df65-46b4-b2d1-c4178b693bd6.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:28:58,900 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:28:58,900 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:28:58,901 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:29:09,334 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:29:09,342 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:29:09,344 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1955' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1981' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/google/genai/_common.py:819: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def is_duck_type_of(obj: Any, cls: type[pydantic.BaseModel]) -> bool:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:29:09,350 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1981' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:29:09,351 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2055' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2056' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:29:09,352 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2056' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:29:09,352 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2057' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2058' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:29:09,353 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2058' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:29:22,451 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:29:55,338 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:30:07,762 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:30:07,762 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:30:07,763 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:30:07,763 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:30:07,764 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:30:15,555 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:30:15,560 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:30:15,562 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2103' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2105' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/tenacity/_utils.py:100: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  dunder_call = partial_call or getattr(call, "__call__", None)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:30:15,563 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2105' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:30:15,564 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2106' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2107' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:30:15,564 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2107' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:30:28,729 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:30:59,513 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:31:10,658 - INFO - > Merging 3 nodes into parent node.
> Parent node id: 3276f80a-ac79-4aa8-9a59-834bf0de7753.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

2026-07-20 22:31:10,659 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6bb9332d-d5cf-4da3-a4a3-27923a9ad689.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 3 nodes into parent node.
> Parent node id: 3276f80a-ac79-4aa8-9a59-834bf0de7753.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 1 nodes into parent node.
> Parent node id: 6bb9332d-d5cf-4da3-a4a3-27923a9ad689.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:31:11,246 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:31:11,247 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:31:11,247 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:31:11,247 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:31:11,248 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:31:21,662 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:31:21,668 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:31:21,672 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2152' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2154' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/aiohttp/client.py:485: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def __init_subclass__(cls: type["ClientSession"]) -> None:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:31:21,676 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2154' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:31:21,676 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2155' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2156' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:31:21,677 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2156' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:31:49,295 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:32:13,130 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:32:23,995 - INFO - > Merging 2 nodes into parent node.
> Parent node id: 138a3f72-1e7e-4d2b-844a-a66d3f1f30d8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

2026-07-20 22:32:23,996 - INFO - > Merging 3 nodes into parent node.
> Parent node id: aca087b6-e6f4-40fd-963c-f0f535a9cde2.
> Parent node text: PAGE 32
In this chapter, I’d like to
discuss some fine points
of finding a job.
The typical job...

2026-07-20 22:32:23,996 - INFO - > Merging 2 nodes into parent node.
> Parent node id: 818ad482-f03a-4610-9137-21b1a4e86bf0.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

2026-07-20 22:32:23,997 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c74aa955-4753-4b68-ab4c-52e24d6d5565.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

2026-07-20 22:32:23,997 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 52e6f948-f684-4c87-8de7-34e642759df8.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

> Merging 2 nodes into parent node.
> Parent node id: 138a3f72-1e7e-4d2b-844a-a66d3f1f30d8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 3 nodes into parent node.
> Parent node id: aca087b6-e6f4-40fd-963c-f0f535a9cde2.
> Parent node text: PAGE 32
In this chapter, I’d like to
discuss some fine points
of finding a job.
The typical job...

> Merging 2 nodes into parent node.
> Parent node id: 818ad482-f03a-4610-9137-21b1a4e86bf0.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

> Merging 1 nodes into parent node.
> Parent node id: c74aa955-4753-4b68-ab4c-52e24d6d5565.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 1 nodes into parent node.
> Parent node id: 52e6f948-f684-4c87-8de7-34e642759df8.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:32:24,704 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:32:24,705 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:32:24,705 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:32:24,705 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:32:24,706 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:32:24,707 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2209' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2211' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/enum.py:1544: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def _get_value(self, flag):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:32:24,711 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2211' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:32:24,711 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2212' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2213' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:32:24,711 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2213' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:32:33,194 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:32:33,200 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:32:50,589 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:33:27,141 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:33:35,261 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:33:35,262 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:33:35,262 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:33:35,263 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:33:35,263 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:33:43,719 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:33:43,722 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2293' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2295' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
Exception ignored in: <coroutine object Kernel.shell_main at 0x32a2e8b40>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
KeyError: '__import__'
Exception ignored in: <coroutine object Kernel.shell_main at 0x32a2e8b40>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
KeyError: '__import__'
2026-07-20 22:33:43,723 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2295' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:33:43,724 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2296' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2297' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
Exception ignored in: <coroutine object Kernel.shell_main at 0x32fcae040>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
KeyError: '__import__'
2026-07-20 22:33:43,724 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2297' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:33:43,726 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:34:16,324 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:34:38,696 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:34:45,883 - INFO - > Merging 5 nodes into parent node.
> Parent node id: 13e014d7-6947-4eba-a1af-15a5e98b3aa0.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

2026-07-20 22:34:45,883 - INFO - > Merging 1 nodes into parent node.
> Parent node id: afc3d6ec-615a-4a60-9562-6d1601fe4e92.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

2026-07-20 22:34:45,883 - INFO - > Merging 3 nodes into parent node.
> Parent node id: 2f65283f-b6ad-4f9a-9d02-a9b0d48bf78f.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

2026-07-20 22:34:45,884 - INFO - > Merging 1 nodes into parent node.
> Parent node id: edcfc49f-f3f4-4ff0-802f-ee37f90488be.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

2026-07-20 22:34:45,884 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 01841a1c-911c-4307-9141-f66e7d6a81b9.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

2026-07-20 22:34:45,884 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 0623f995-15e3-429c-a2a3-77e5b53659cb.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

> Merging 5 nodes into parent node.
> Parent node id: 13e014d7-6947-4eba-a1af-15a5e98b3aa0.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

> Merging 1 nodes into parent node.
> Parent node id: afc3d6ec-615a-4a60-9562-6d1601fe4e92.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

> Merging 3 nodes into parent node.
> Parent node id: 2f65283f-b6ad-4f9a-9d02-a9b0d48bf78f.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

> Merging 1 nodes into parent node.
> Parent node id: edcfc49f-f3f4-4ff0-802f-ee37f90488be.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

> Merging 1 nodes into parent node.
> Parent node id: 01841a1c-911c-4307-9141-f66e7d6a81b9.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

> Merging 1 nodes into parent node.
> Parent node id: 0623f995-15e3-429c-a2a3-77e5b53659cb.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:34:46,415 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:34:46,415 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:34:46,416 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:34:46,416 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:34:46,417 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:34:48,126 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2376' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2378' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/sugar/socket.py:736: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  for i, msg in enumerate(msg_parts):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:34:48,131 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2378' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:34:48,131 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2379' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2380' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:34:48,131 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2380' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:34:58,512 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:34:58,519 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:35:10,071 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:35:27,725 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:35:41,710 - INFO - > Merging 3 nodes into parent node.
> Parent node id: 13e014d7-6947-4eba-a1af-15a5e98b3aa0.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

2026-07-20 22:35:41,710 - INFO - > Merging 1 nodes into parent node.
> Parent node id: afc3d6ec-615a-4a60-9562-6d1601fe4e92.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

2026-07-20 22:35:41,710 - INFO - > Merging 3 nodes into parent node.
> Parent node id: 2f65283f-b6ad-4f9a-9d02-a9b0d48bf78f.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

2026-07-20 22:35:41,711 - INFO - > Merging 1 nodes into parent node.
> Parent node id: edcfc49f-f3f4-4ff0-802f-ee37f90488be.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

2026-07-20 22:35:41,711 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 01841a1c-911c-4307-9141-f66e7d6a81b9.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

2026-07-20 22:35:41,711 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 0623f995-15e3-429c-a2a3-77e5b53659cb.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

> Merging 3 nodes into parent node.
> Parent node id: 13e014d7-6947-4eba-a1af-15a5e98b3aa0.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

> Merging 1 nodes into parent node.
> Parent node id: afc3d6ec-615a-4a60-9562-6d1601fe4e92.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

> Merging 3 nodes into parent node.
> Parent node id: 2f65283f-b6ad-4f9a-9d02-a9b0d48bf78f.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

> Merging 1 nodes into parent node.
> Parent node id: edcfc49f-f3f4-4ff0-802f-ee37f90488be.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

> Merging 1 nodes into parent node.
> Parent node id: 01841a1c-911c-4307-9141-f66e7d6a81b9.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

> Merging 1 nodes into parent node.
> Parent node id: 0623f995-15e3-429c-a2a3-77e5b53659cb.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:35:42,213 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:35:42,213 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:35:42,214 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:35:42,214 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:35:42,215 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:35:49,543 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:35:49,562 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:36:01,078 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:36:16,139 - INFO - AFC is enabled with max remote calls: 10.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:36:25,916 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:36:25,917 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:36:25,918 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:36:25,918 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:36:25,919 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:36:35,506 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:36:35,511 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:36:35,513 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2497' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2499' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/pydantic/_internal/_utils.py:446: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  return self.fget.__get__(instance, objtype)()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:36:35,519 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2499' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:36:35,520 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2500' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2501' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:36:35,520 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2501' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:36:55,717 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:37:13,825 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:37:21,280 - INFO - > Merging 4 nodes into parent node.
> Parent node id: d25e3176-db87-47dc-8570-7f853875dbf4.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

2026-07-20 22:37:21,281 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c75e4c90-c1e6-4c8e-936f-6f8efbc019cd.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 4 nodes into parent node.
> Parent node id: d25e3176-db87-47dc-8570-7f853875dbf4.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 1 nodes into parent node.
> Parent node id: c75e4c90-c1e6-4c8e-936f-6f8efbc019cd.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:37:21,853 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:37:21,854 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:37:21,855 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:37:21,855 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:37:21,856 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:37:22,383 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2559' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2561' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/enum.py:1568: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  if self._get_value(flag) is None:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:37:22,402 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2561' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:37:22,403 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2562' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2563' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:37:22,403 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2563' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:37:32,744 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:37:32,749 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:37:44,901 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:38:05,475 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:38:16,933 - INFO - > Merging 3 nodes into parent node.
> Parent node id: 13e014d7-6947-4eba-a1af-15a5e98b3aa0.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

2026-07-20 22:38:16,934 - INFO - > Merging 1 nodes into parent node.
> Parent node id: edcfc49f-f3f4-4ff0-802f-ee37f90488be.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

> Merging 3 nodes into parent node.
> Parent node id: 13e014d7-6947-4eba-a1af-15a5e98b3aa0.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

> Merging 1 nodes into parent node.
> Parent node id: edcfc49f-f3f4-4ff0-802f-ee37f90488be.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:38:17,617 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:38:17,618 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:38:17,618 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:38:17,619 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:38:17,619 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:38:27,726 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:38:27,728 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:38:27,729 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2620' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2622' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py:249: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  _iterencode = c_make_encoder(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-07-20 22:38:27,730 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2622' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:38:27,730 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2623' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2624' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:38:27,730 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2624' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:38:51,475 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:39:09,471 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:39:28,766 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 8ece249b-1195-41c1-a02a-7022b65beb0a.
> Parent node text: If you’re leaving
a job, exit gracefully. Give your employer ample notice, give your full effort...

2026-07-20 22:39:28,767 - INFO - > Merging 1 nodes into parent node.
> Parent node id: e5e7748f-a13e-4881-ba29-6cc7a0b8ce28.
> Parent node text: PAGE 31
Finding the Right
AI Job for You
CHAPTER 9
JOBS

2026-07-20 22:39:28,767 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 505eaae8-c1f5-45ef-9c1d-b454234d80c0.
> Parent node text: PAGE 31
Finding the Right
AI Job for You
CHAPTER 9
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 8ece249b-1195-41c1-a02a-7022b65beb0a.
> Parent node text: If you’re leaving
a job, exit gracefully. Give your employer ample notice, give your full effort...

> Merging 1 nodes into parent node.
> Parent node id: e5e7748f-a13e-4881-ba29-6cc7a0b8ce28.
> Parent node text: PAGE 31
Finding the Right
AI Job for You
CHAPTER 9
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 505eaae8-c1f5-45ef-9c1d-b454234d80c0.
> Parent node text: PAGE 31
Finding the Right
AI Job for You
CHAPTER 9
JOBS

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:39:29,893 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:39:29,893 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:39:29,894 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:39:29,894 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x104bf3f80> is already entered
2026-07-20 22:39:29,895 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:39:39,533 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:39:39,539 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:39:39,541 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2679' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2681' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:39:39,541 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2681' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:39:39,542 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2682' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-2683' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:39:39,542 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2683' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:40:14,722 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:40:38,690 - INFO - AFC is enabled with max remote calls: 10.

,app_id,question,answer,answer_relevancy,context_relevancy,groundedness
0,automerging,What are the keys to building a career in AI?,The keys to building a career in AI include th...,1.0,0.875,1.0
1,automerging,How can teamwork contribute to success in AI?,Teamwork contributes to success in AI because ...,1.0,0.875,1.0
2,automerging,What is the importance of networking in AI?,A strong professional network is important bec...,0.0,1.000,1.0
3,automerging,What are some good habits to develop for a suc...,Many successful people develop good habits in ...,0.5,0.875,1.0
4,automerging,How can altruism be beneficial in building a c...,People who aim to lift others during every ste...,0.5,0.750,1.0

In [33]:
for _, row in records_automerging.iterrows():
    print(row["question"])
    print(str(row["answer"])[:300], "...")
    print(
        "AR/CR/G:",
        row["answer_relevancy"],
        row["context_relevancy"],
        row["groundedness"],
    )
    print("---")

What are the keys to building a career in AI?
The keys to building a career in AI include three primary steps: learning foundational technical skills, working on projects, and finding a job. These steps are supported by being part of a community. Additionally, it is critical to prioritize topic selection when learning and to develop the ability ...
AR/CR/G: 1.0 0.875 1.0
---
How can teamwork contribute to success in AI?
Teamwork contributes to success in AI because large projects are handled more successfully when worked on in teams rather than individually. This involves the critical ability to collaborate with, influence, and be influenced by others, making interpersonal and communication skills very important. ...
AR/CR/G: 1.0 0.875 1.0
---
What is the importance of networking in AI?
A strong professional network is important because it can propel you forward when you need advice or help. Additionally, having a network within a specific industry helps a professional and can make future job searches easier. Instead of traditional networking, focusing on building up communities ca ...
AR/CR/G: 0.0 1.0 1.0
---
What are some good habits to develop for a successful career?
Many successful people develop good habits in the following areas:
* Eating
* Exercise
* Sleep
* Personal relationships
* Work
* Learning
* Self-care ...
AR/CR/G: 0.5 0.875 1.0
---
How can altruism be beneficial in building a career?
People who aim to lift others during every step of their own journey often achieve better outcomes for themselves. ...
AR/CR/G: 0.5 0.75 1.0
---
What is imposter syndrome and how does it relate to AI?
Imposter syndrome is a feeling where an individual, regardless of their success in a field, wonders if they are a fraud and whether they truly belong in a community. In the context of AI, this experience occurs even among accomplished people. Because AI is technically complex and contains many smart ...
AR/CR/G: 1.0 1.0 1.0
---
Who are some accomplished individuals who have experienced imposter syndrome?
Accomplished individuals who have spoken publicly about experiencing imposter syndrome include former Facebook COO Sheryl Sandberg, U.S. first lady Michelle Obama, actor Tom Hanks, and Atlassian co-CEO Mike Cannon-Brookes. ...
AR/CR/G: 1.0 1.0 1.0
---
What is the first step to becoming good at AI?
The first step to becoming good at AI is to suck at it. ...
AR/CR/G: 1.0 1.0 1.0
---
What are some common challenges in AI?
Common challenges in AI include:

*   Finding suitable projects.
*   Setting expectations and estimating a project's return on investment and timeline.
*   Project management difficulties resulting from the iterative nature of AI, such as not knowing beforehand how long it will take to reach target  ...
AR/CR/G: 1.0 0.75 1.0
---
Is it normal to find parts of AI challenging?
Yes, it is normal to find parts of AI challenging. AI is technically complex, and the author notes that everyone has been in that position, including those who have published seminal AI papers. Even the author has struggled with the math behind linear regression, bugs in neural network implementatio ...
AR/CR/G: 1.0 1.0 1.0
---
What is the right AI job for me?
The provided text does not contain information on how to determine the right AI job for an individual; it only lists a chapter titled "Finding the Right AI Job for You" and provides guidance on how to exit a job gracefully. ...
AR/CR/G: 1.0 0.5 1.0
---

In [34]:
import pandas as pd

comparison = pd.concat(
    [
        summarize_eval_df(records_basic),
        summarize_eval_df(records_sentence),
        summarize_eval_df(records_automerging),
    ],
    ignore_index=True,
)
comparison

               app_id  answer_relevancy  context_relevancy  groundedness
0  basic_query_engine          0.818182           0.897727           1.0
1     sentence_window          0.818182           0.897727           1.0
2         automerging          0.818182           0.875000           1.0

In [35]:
print("Pipeline comparison complete.")

Pipeline comparison complete.