# Lesson 4: Auto-merging Retrieval

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import utils

import os

In [4]:
from llama_index.core import SimpleDirectoryReader

documents = SimpleDirectoryReader(
    input_files=["./eBook-How-to-Build-a-Career-in-AI.pdf"]
).load_data()

In [5]:
print(type(documents), "\n")
print(len(documents), "\n")
print(type(documents[0]))
print(documents[0])

<class 'list'>

41

<class 'llama_index.core.schema.Document'>
Doc ID: 92278488-2374-4840-9597-a01868969fba
Text: PAGE 1 Founder, DeepLearning.AI Collected Insights from Andrew
Ng How to  Build Your Career in AI A Simple Guide

## Auto-merging retrieval setup

In [8]:
from llama_index.core import Document

document = Document(text="\n\n".join([doc.text for doc in documents]))

In [9]:
from llama_index.core.node_parser import HierarchicalNodeParser

# create the hierarchical node parser w/ default settings
node_parser = HierarchicalNodeParser.from_defaults(
    chunk_sizes=[2048, 512, 128]
)

In [10]:
nodes = node_parser.get_nodes_from_documents([document])

In [11]:
from llama_index.core.node_parser import get_leaf_nodes

leaf_nodes = get_leaf_nodes(nodes)
print(leaf_nodes[30].text)

Of course, I also encourage learning driven by curiosity. If something interests you, go ahead
and learn it regardless of how useful it might turn out to be!  Maybe this will lead to a creative
spark or technical breakthrough.
How much math do you need to know to be a machine learning engineer?

In [12]:
nodes_by_id = {node.node_id: node for node in nodes}

parent_node = nodes_by_id[leaf_nodes[30].parent_node.node_id]
print(parent_node.text)

On some days, maybe you’ll end up studying for an
hour or longer.

PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? It’s always nice to know more math! But there’s so much to
learn that, realistically, it’s necessary to prioritize. Here’s how you might go about strengthening
your math background.
To figure out what’s important to know, I find it useful to ask what you need to know to make
the decisions required for the work you want to do. At DeepLearning.AI, we frequently ask,
“What does someone need to know to accomplish their goals?” The goal might be building a
machine learning model, architecting a system, or passing a job interview.
Understanding the math behind algorithms you use is often helpful, since it enables you to
debug them. But the depth of knowledge that’s useful changes over time. As machine learning
techniques mature and become more reliable and turnkey, they require less debugging, and a
shallower understanding of the math involved may be sufficient to make them work.
For instance, in an earlier era of machine learning, linear algebra libraries for solving linear
systems of equations (for linear regression) were immature. I had to understand how these
libraries worked so I could choose among different libraries and avoid numerical roundoff
pitfalls. But this became less important as numerical linear algebra libraries matured.
Deep learning is still an emerging technology, so when you train a neural network and the
optimization algorithm struggles to converge, understanding the math behind gradient
descent, momentum, and the Adam optimization algorithm will help you make better decisions.
Similarly, if your neural network does something funny — say, it makes bad predictions on
images of a certain resolution, but not others — understanding the math behind neural network
architectures puts you in a better position to figure out what to do.
Of course, I also encourage learning driven by curiosity. If something interests you, go ahead
and learn it regardless of how useful it might turn out to be!  Maybe this will lead to a creative
spark or technical breakthrough.
How much math do you need to know to be a machine learning engineer?

### Building the index

In [14]:
from llama_index.llms.google_genai import GoogleGenAI

llm = GoogleGenAI(
    model="gemma-4-31b-it",
    api_key=utils.get_google_api_key(),
    temperature=0.1,
)

2026-07-20 22:44:01,322 - INFO - HTTP Request: GET https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it "HTTP/1.1 200 OK"

In [15]:
from llama_index.core import Settings
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

Settings.llm = llm
Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

2026-07-20 22:44:05,490 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:05,514 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 22:44:05,803 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-07-20 22:44:05,805 - WARNING - Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-07-20 22:44:05,882 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 22:44:05,885 - INFO - Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-07-20 22:44:06,257 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:06,279 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 22:44:06,557 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:06,588 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-07-20 22:44:06,931 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:06,953 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 22:44:07,228 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:07,250 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-07-20 22:44:07,552 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:44:07,817 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:07,841 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

2026-07-20 22:44:08,268 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:44:08,555 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:44:08,841 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:44:09,128 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:44:09,421 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:09,443 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:44:09,720 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:09,741 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 22:44:10,145 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:10,167 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 22:44:10,451 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:10,474 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:44:10,762 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-20 22:44:11,167 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-20 22:44:11,493 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:11,517 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-07-20 22:44:11,806 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-07-20 22:44:12,189 - INFO - Loaded 1 prompt with these keys: ['query']

In [16]:
from llama_index.core import VectorStoreIndex, StorageContext

storage_context = StorageContext.from_defaults()
storage_context.docstore.add_documents(nodes)

automerging_index = VectorStoreIndex(leaf_nodes, storage_context=storage_context)

automerging_index.storage_context.persist(persist_dir="./merging_index")

In [17]:
# This block of code is optional to check
# if an index file exist, then it will load it
# if not, it will rebuild it

import os
from llama_index.core import VectorStoreIndex, StorageContext, load_index_from_storage

if not os.path.exists("./merging_index"):
    storage_context = StorageContext.from_defaults()
    storage_context.docstore.add_documents(nodes)

    automerging_index = VectorStoreIndex(
            leaf_nodes,
            storage_context=storage_context,
        )

    automerging_index.storage_context.persist(persist_dir="./merging_index")
else:
    automerging_index = load_index_from_storage(
        StorageContext.from_defaults(persist_dir="./merging_index")
    )

2026-07-20 22:44:13,709 - INFO - Loading all indices.

### Defining the retriever and running the query engine

In [18]:
from llama_index.core.postprocessor import SentenceTransformerRerank
from llama_index.core.retrievers import AutoMergingRetriever
from llama_index.core.query_engine import RetrieverQueryEngine

automerging_retriever = automerging_index.as_retriever(
    similarity_top_k=12
)

retriever = AutoMergingRetriever(
    automerging_retriever, 
    automerging_index.storage_context, 
    verbose=True
)

rerank = SentenceTransformerRerank(top_n=6, model="BAAI/bge-reranker-base")

auto_merging_engine = RetrieverQueryEngine.from_args(
    automerging_retriever, node_postprocessors=[rerank]
)

2026-07-20 22:44:14,037 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/modules.json "HTTP/1.1 404 Not Found"
2026-07-20 22:44:14,039 - INFO - No modules.json found for BAAI/bge-reranker-base, initializing a new CrossEncoder model.
2026-07-20 22:44:14,314 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"
2026-07-20 22:44:14,594 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:14,616 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:44:14,905 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:44:15,208 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:15,230 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

2026-07-20 22:44:15,884 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:44:16,177 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:44:16,489 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:44:16,903 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:44:17,205 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:17,239 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:44:17,571 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:17,594 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:44:18,002 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:18,023 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:44:18,323 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:44:18,482 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:44:18,775 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-20 22:44:19,063 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-20 22:44:20,324 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"

In [19]:
auto_merging_response = auto_merging_engine.query(
    "What is the importance of networking in AI?"
)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:44:22,096 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:44:35,025 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"

In [21]:
from llama_index.core.response.notebook_utils import display_response

display_response(auto_merging_response)

**`Final Response:`** A strong professional network in AI is important because it can help propel you forward when you need advice or help. Beyond providing valuable information, people in your network can play an invaluable role by referring you to potential employers. Additionally, welcoming others into the AI community can help others recognize your expertise and encourage you to continue developing, while also reducing doubts that you are a member of the community.

## Putting it all Together

In [22]:
from utils import build_automerging_index, get_automerging_query_engine

In [23]:
from llama_index.llms.google_genai import GoogleGenAI

index = build_automerging_index(
    [document],
    llm=GoogleGenAI(
        model="gemini-2.5-flash",
        api_key=utils.get_google_api_key(),
        temperature=0.1,
    ),
    save_dir="./merging_index",
)

2026-07-20 22:52:36,702 - INFO - HTTP Request: GET https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash "HTTP/1.1 200 OK"
2026-07-20 22:52:37,335 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:37,355 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 22:52:37,634 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:37,746 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 22:52:37,748 - INFO - Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-07-20 22:52:38,118 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:38,139 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 22:52:38,427 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:38,447 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-07-20 22:52:38,765 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:38,799 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 22:52:39,094 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:39,179 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:39,454 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:39,737 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:39,757 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

2026-07-20 22:52:40,123 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:40,422 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:40,742 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:41,015 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:41,284 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:41,305 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:41,576 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:41,596 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:41,867 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:41,888 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:42,171 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:42,191 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:42,492 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-20 22:52:42,835 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-20 22:52:43,150 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:43,170 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-07-20 22:52:43,444 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-07-20 22:52:43,806 - INFO - Loaded 1 prompt with these keys: ['query']
2026-07-20 22:52:43,941 - INFO - Loading all indices.

In [24]:
query_engine = get_automerging_query_engine(index, similarity_top_k=6)

2026-07-20 22:52:44,212 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/modules.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:44,215 - INFO - No modules.json found for BAAI/bge-reranker-base, initializing a new CrossEncoder model.
2026-07-20 22:52:44,507 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"
2026-07-20 22:52:44,784 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:44,817 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:45,103 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:45,529 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:45,549 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

2026-07-20 22:52:45,947 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:46,228 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:46,554 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:46,831 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:47,167 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:47,188 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:47,577 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:47,597 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:47,883 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:47,903 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:48,192 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:48,213 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:48,491 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-20 22:52:48,804 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-20 22:52:50,445 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"

## Evaluation (LlamaIndex RAG triad)

In [25]:
from utils import get_eval_llm, evaluate_query_engine, summarize_eval_df

eval_llm = get_eval_llm()

2026-07-20 22:52:51,839 - INFO - HTTP Request: GET https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it "HTTP/1.1 200 OK"

### Two layers

In [26]:
auto_merging_index_0 = build_automerging_index(
    documents,
    llm=GoogleGenAI(
        model="gemma-4-31b-it",
        api_key=utils.get_google_api_key(),
        temperature=0.1,
    ),
    embed_model="local:BAAI/bge-small-en-v1.5",
    save_dir="merging_index_0",
    chunk_sizes=[2048,512],
)

2026-07-20 22:52:52,122 - INFO - HTTP Request: GET https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it "HTTP/1.1 200 OK"
2026-07-20 22:52:52,435 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:52,455 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 22:52:52,798 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:52,815 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 22:52:52,817 - INFO - Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-07-20 22:52:53,099 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:53,121 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-20 22:52:53,478 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:53,499 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-07-20 22:52:53,775 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:53,859 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-20 22:52:54,183 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:54,204 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:54,493 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:55,005 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:55,026 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

2026-07-20 22:52:55,418 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:55,742 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:56,073 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:56,378 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:52:56,752 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:56,787 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:57,150 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:57,170 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:57,516 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:57,535 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:57,829 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:57,846 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:52:58,199 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-20 22:52:58,564 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-20 22:52:58,876 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:52:58,897 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-07-20 22:52:59,248 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-07-20 22:53:00,107 - INFO - Loaded 1 prompt with these keys: ['query']

In [27]:
auto_merging_engine_0 = get_automerging_query_engine(
    auto_merging_index_0,
    similarity_top_k=12,
    rerank_top_n=6,
)

2026-07-20 22:53:00,976 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/modules.json "HTTP/1.1 404 Not Found"
2026-07-20 22:53:00,979 - INFO - No modules.json found for BAAI/bge-reranker-base, initializing a new CrossEncoder model.
2026-07-20 22:53:01,277 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"
2026-07-20 22:53:01,554 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:53:01,574 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:53:01,852 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:53:02,133 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:53:02,153 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

2026-07-20 22:53:02,516 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:53:02,786 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:53:03,141 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:53:03,418 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-20 22:53:03,696 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:53:03,716 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:53:04,003 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:53:04,023 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:53:04,372 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:53:04,391 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-20 22:53:04,683 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-20 22:53:04,704 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-20 22:53:05,087 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-20 22:53:05,379 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-20 22:53:06,600 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"

In [28]:
eval_questions = []
with open("generated_questions.text", "r") as file:
    for line in file:
        item = line.strip()
        if item:
            eval_questions.append(item)

In [29]:
records_app0 = evaluate_query_engine(
    auto_merging_engine_0,
    eval_questions,
    app_id="app_0",
    llm=eval_llm,
)
records_app0.head()

2026-07-20 22:53:07,455 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 31158589-a647-46bd-bacf-a0ffdaabb696.
> Parent node text: PAGE 26
If you’re considering a role switch, a startup can be an easier place to do it than a big...

2026-07-20 22:53:07,456 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 427dcb81-2e10-424d-b5c2-c1972362e7c7.
> Parent node text: PAGE 25
Finding a job has a few predictable steps that include selecting the companies to which y...

2026-07-20 22:53:07,456 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

2026-07-20 22:53:07,457 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 22:53:07,457 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

2026-07-20 22:53:07,457 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 22:53:07,458 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 22:53:07,458 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

2026-07-20 22:53:07,459 - INFO - > Merging 2 nodes into parent node.
> Parent node id: 43509715-5add-4975-a56b-bdb17b98e53c.
> Parent node text: PAGE 32
In this chapter, I’d like to
discuss some fine points
of finding a job.
The typical job...

2026-07-20 22:53:07,459 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 1 nodes into parent node.
> Parent node id: 31158589-a647-46bd-bacf-a0ffdaabb696.
> Parent node text: PAGE 26
If you’re considering a role switch, a startup can be an easier place to do it than a big...

> Merging 1 nodes into parent node.
> Parent node id: 427dcb81-2e10-424d-b5c2-c1972362e7c7.
> Parent node text: PAGE 25
Finding a job has a few predictable steps that include selecting the companies to which y...

> Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

> Merging 2 nodes into parent node.
> Parent node id: 43509715-5add-4975-a56b-bdb17b98e53c.
> Parent node text: PAGE 32
In this chapter, I’d like to
discuss some fine points
of finding a job.
The typical job...

> Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:53:07,912 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:53:21,985 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:53:22,005 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:53:35,119 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:54:02,597 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:54:16,368 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 037d6910-75d4-4bca-be46-5c7e1e313ad5.
> Parent node text: PAGE 27
There’s a lot we don’t know about the future: When will we cure Alzheimer’s disease? Who ...

2026-07-20 22:54:16,369 - INFO - > Merging 2 nodes into parent node.
> Parent node id: 26d9d53a-9bf4-4293-bc6f-cb8dc9a7e993.
> Parent node text: PAGE 20
Working on projects requires making tough choices about what to build and how to go
abou...

2026-07-20 22:54:16,369 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

2026-07-20 22:54:16,369 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

2026-07-20 22:54:16,369 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 22:54:16,370 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

2026-07-20 22:54:16,370 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 22:54:16,370 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

2026-07-20 22:54:16,370 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

2026-07-20 22:54:16,370 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 1 nodes into parent node.
> Parent node id: 037d6910-75d4-4bca-be46-5c7e1e313ad5.
> Parent node text: PAGE 27
There’s a lot we don’t know about the future: When will we cure Alzheimer’s disease? Who ...

> Merging 2 nodes into parent node.
> Parent node id: 26d9d53a-9bf4-4293-bc6f-cb8dc9a7e993.
> Parent node text: PAGE 20
Working on projects requires making tough choices about what to build and how to go
abou...

> Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

> Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

> Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

> Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:54:17,111 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x1076c1b40> is already entered
2026-07-20 22:54:17,114 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:54:34,301 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:54:34,308 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:54:49,421 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-125' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:54:49,423 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-124' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-125' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:54:49,442 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:55:11,633 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:55:28,267 - INFO - > Merging 2 nodes into parent node.
> Parent node id: 26d9d53a-9bf4-4293-bc6f-cb8dc9a7e993.
> Parent node text: PAGE 20
Working on projects requires making tough choices about what to build and how to go
abou...

2026-07-20 22:55:28,267 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 22:55:28,267 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

2026-07-20 22:55:28,268 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 22:55:28,268 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 22:55:28,268 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

2026-07-20 22:55:28,268 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 22:55:28,268 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

2026-07-20 22:55:28,269 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

2026-07-20 22:55:28,269 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 037d6910-75d4-4bca-be46-5c7e1e313ad5.
> Parent node text: PAGE 27
There’s a lot we don’t know about the future: When will we cure Alzheimer’s disease? Who ...

2026-07-20 22:55:28,269 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 2 nodes into parent node.
> Parent node id: 26d9d53a-9bf4-4293-bc6f-cb8dc9a7e993.
> Parent node text: PAGE 20
Working on projects requires making tough choices about what to build and how to go
abou...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

> Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

> Merging 1 nodes into parent node.
> Parent node id: 037d6910-75d4-4bca-be46-5c7e1e313ad5.
> Parent node text: PAGE 27
There’s a lot we don’t know about the future: When will we cure Alzheimer’s disease? Who ...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:55:29,047 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:55:30,612 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 503 Service Unavailable"
2026-07-20 22:55:30,615 - WARNING - Retrying llama_index.llms.google_genai.base.GoogleGenAI._chat in 1 seconds as it raised ServerError: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}.
2026-07-20 22:55:31,622 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:56:00,132 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:56:00,152 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:56:15,726 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:56:46,144 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:57:18,570 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

2026-07-20 22:57:18,571 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 22:57:18,571 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 22:57:18,572 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 22:57:18,572 - INFO - > Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

2026-07-20 22:57:18,572 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

2026-07-20 22:57:18,573 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 22:57:18,573 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

2026-07-20 22:57:18,573 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

2026-07-20 22:57:18,573 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

2026-07-20 22:57:18,573 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

> Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

> Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:57:19,449 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:57:47,663 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:57:47,680 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:57:59,913 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:58:34,082 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:59:12,527 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

2026-07-20 22:59:12,528 - INFO - > Merging 2 nodes into parent node.
> Parent node id: 0172cff2-2e17-4235-8df9-0af3a2da9c34.
> Parent node text: PAGE 9
In the previous chapter, I introduced three key steps for building a career in AI: learnin...

2026-07-20 22:59:12,528 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

2026-07-20 22:59:12,528 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d9eb88e4-8c7a-45dc-8e60-692a9551a539.
> Parent node text: PAGE 10
This is a lot to learn!
Even after you master everything on this list, I hope you’ll keep...

2026-07-20 22:59:12,528 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 22:59:12,528 - INFO - > Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

2026-07-20 22:59:12,529 - INFO - > Merging 1 nodes into parent node.
> Parent node id: e8b5b912-693c-47b4-9259-f537271f7ed2.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

2026-07-20 22:59:12,529 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 22:59:12,529 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 22:59:12,529 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

2026-07-20 22:59:12,529 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

> Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

> Merging 2 nodes into parent node.
> Parent node id: 0172cff2-2e17-4235-8df9-0af3a2da9c34.
> Parent node text: PAGE 9
In the previous chapter, I introduced three key steps for building a career in AI: learnin...

> Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

> Merging 1 nodes into parent node.
> Parent node id: d9eb88e4-8c7a-45dc-8e60-692a9551a539.
> Parent node text: PAGE 10
This is a lot to learn!
Even after you master everything on this list, I hope you’ll keep...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

> Merging 1 nodes into parent node.
> Parent node id: e8b5b912-693c-47b4-9259-f537271f7ed2.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 22:59:13,349 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x1076c1b40> is already entered
2026-07-20 22:59:13,350 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x1076c1b40> is already entered
2026-07-20 22:59:13,350 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:59:36,624 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 22:59:36,630 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 22:59:36,633 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-197' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-198' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:59:36,634 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-198' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:59:36,634 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-199' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-200' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-20 22:59:36,635 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-200' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>
2026-07-20 22:59:51,587 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:00:16,977 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:00:37,449 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d9eb88e4-8c7a-45dc-8e60-692a9551a539.
> Parent node text: PAGE 10
This is a lot to learn!
Even after you master everything on this list, I hope you’ll keep...

2026-07-20 23:00:37,449 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:00:37,449 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 1267eff1-6091-4291-84d1-44e633e33041.
> Parent node text: PAGE 8
Learning Technical
Skills for a Promising
AI Career
CHAPTER 2
LEARNING

2026-07-20 23:00:37,450 - INFO - > Merging 2 nodes into parent node.
> Parent node id: 0172cff2-2e17-4235-8df9-0af3a2da9c34.
> Parent node text: PAGE 9
In the previous chapter, I introduced three key steps for building a career in AI: learnin...

2026-07-20 23:00:37,450 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

2026-07-20 23:00:37,450 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 23:00:37,450 - INFO - > Merging 1 nodes into parent node.
> Parent node id: a3d9829b-ab51-4963-8911-25dd6d0421ea.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

2026-07-20 23:00:37,450 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 23:00:37,451 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 23:00:37,451 - INFO - > Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

2026-07-20 23:00:37,451 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: d9eb88e4-8c7a-45dc-8e60-692a9551a539.
> Parent node text: PAGE 10
This is a lot to learn!
Even after you master everything on this list, I hope you’ll keep...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: 1267eff1-6091-4291-84d1-44e633e33041.
> Parent node text: PAGE 8
Learning Technical
Skills for a Promising
AI Career
CHAPTER 2
LEARNING

> Merging 2 nodes into parent node.
> Parent node id: 0172cff2-2e17-4235-8df9-0af3a2da9c34.
> Parent node text: PAGE 9
In the previous chapter, I introduced three key steps for building a career in AI: learnin...

> Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: a3d9829b-ab51-4963-8911-25dd6d0421ea.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:00:38,163 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x1076c1b40> is already entered
2026-07-20 23:00:38,165 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x1076c1b40> is already entered
2026-07-20 23:00:38,166 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:00:51,981 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:00:51,992 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:01:05,662 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:01:35,487 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:01:48,569 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

2026-07-20 23:01:48,569 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 31158589-a647-46bd-bacf-a0ffdaabb696.
> Parent node text: PAGE 26
If you’re considering a role switch, a startup can be an easier place to do it than a big...

2026-07-20 23:01:48,569 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

2026-07-20 23:01:48,570 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 427dcb81-2e10-424d-b5c2-c1972362e7c7.
> Parent node text: PAGE 25
Finding a job has a few predictable steps that include selecting the companies to which y...

2026-07-20 23:01:48,570 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

2026-07-20 23:01:48,570 - INFO - > Merging 1 nodes into parent node.
> Parent node id: b152f8e3-18ae-4b1e-974c-7398fdabf3e9.
> Parent node text: PAGE 28
Using Informational
Interviews to Find
the Right Job
CHAPTER 8
JOBS

2026-07-20 23:01:48,570 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:01:48,570 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:01:48,570 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 23:01:48,571 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

> Merging 1 nodes into parent node.
> Parent node id: 31158589-a647-46bd-bacf-a0ffdaabb696.
> Parent node text: PAGE 26
If you’re considering a role switch, a startup can be an easier place to do it than a big...

> Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

> Merging 1 nodes into parent node.
> Parent node id: 427dcb81-2e10-424d-b5c2-c1972362e7c7.
> Parent node text: PAGE 25
Finding a job has a few predictable steps that include selecting the companies to which y...

> Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

> Merging 1 nodes into parent node.
> Parent node id: b152f8e3-18ae-4b1e-974c-7398fdabf3e9.
> Parent node text: PAGE 28
Using Informational
Interviews to Find
the Right Job
CHAPTER 8
JOBS

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:01:49,322 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:02:16,361 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:02:16,393 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:02:29,796 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:02:55,856 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:03:31,731 - INFO - > Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

2026-07-20 23:03:31,732 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

2026-07-20 23:03:31,733 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

2026-07-20 23:03:31,733 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

2026-07-20 23:03:31,733 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 23:03:31,733 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:03:31,733 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

2026-07-20 23:03:31,733 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:03:31,734 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 23:03:31,734 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

2026-07-20 23:03:31,734 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

> Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

> Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

> Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

> Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:03:32,440 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:03:58,790 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:03:58,797 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:04:12,782 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:04:44,754 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:05:07,912 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

2026-07-20 23:05:07,912 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:05:07,912 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 23:05:07,913 - INFO - > Merging 1 nodes into parent node.
> Parent node id: b152f8e3-18ae-4b1e-974c-7398fdabf3e9.
> Parent node text: PAGE 28
Using Informational
Interviews to Find
the Right Job
CHAPTER 8
JOBS

2026-07-20 23:05:07,913 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

2026-07-20 23:05:07,913 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:05:07,913 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

2026-07-20 23:05:07,913 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

2026-07-20 23:05:07,913 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

2026-07-20 23:05:07,913 - INFO - > Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

> Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: b152f8e3-18ae-4b1e-974c-7398fdabf3e9.
> Parent node text: PAGE 28
Using Informational
Interviews to Find
the Right Job
CHAPTER 8
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

> Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:05:08,635 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:05:29,078 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:05:29,084 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:05:46,009 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:06:19,669 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:06:37,468 - INFO - > Merging 1 nodes into parent node.
> Parent node id: b152f8e3-18ae-4b1e-974c-7398fdabf3e9.
> Parent node text: PAGE 28
Using Informational
Interviews to Find
the Right Job
CHAPTER 8
JOBS

2026-07-20 23:06:37,468 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

2026-07-20 23:06:37,469 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

2026-07-20 23:06:37,469 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d71aeeb6-0924-4046-b62f-5fc718a39686.
> Parent node text: PAGE 31
Finding the Right
AI Job for You
CHAPTER 9
JOBS

2026-07-20 23:06:37,469 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

2026-07-20 23:06:37,469 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 8108c9c3-5c36-451c-b552-a9e329996ab6.
> Parent node text: PAGE 34
Keys to Building a
Career in AI
CHAPTER 10
JOBS

2026-07-20 23:06:37,469 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

2026-07-20 23:06:37,470 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

2026-07-20 23:06:37,470 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

2026-07-20 23:06:37,470 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 3b9166f3-dfbb-48eb-8c71-ae56958763dd.
> Parent node text: PAGE 21
Building a Portfolio of
Projects that Shows
Skill Progression
CHAPTER 6
PROJECTS

2026-07-20 23:06:37,470 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 1 nodes into parent node.
> Parent node id: b152f8e3-18ae-4b1e-974c-7398fdabf3e9.
> Parent node text: PAGE 28
Using Informational
Interviews to Find
the Right Job
CHAPTER 8
JOBS

> Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

> Merging 1 nodes into parent node.
> Parent node id: d71aeeb6-0924-4046-b62f-5fc718a39686.
> Parent node text: PAGE 31
Finding the Right
AI Job for You
CHAPTER 9
JOBS

> Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

> Merging 1 nodes into parent node.
> Parent node id: 8108c9c3-5c36-451c-b552-a9e329996ab6.
> Parent node text: PAGE 34
Keys to Building a
Career in AI
CHAPTER 10
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

> Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

> Merging 1 nodes into parent node.
> Parent node id: 3b9166f3-dfbb-48eb-8c71-ae56958763dd.
> Parent node text: PAGE 21
Building a Portfolio of
Projects that Shows
Skill Progression
CHAPTER 6
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:06:38,183 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:07:03,797 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:07:03,809 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:07:19,427 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:07:48,583 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:08:07,902 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 23:08:07,903 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 23:08:07,903 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

2026-07-20 23:08:07,904 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:08:07,904 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

2026-07-20 23:08:07,904 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 23:08:07,905 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 3b9166f3-dfbb-48eb-8c71-ae56958763dd.
> Parent node text: PAGE 21
Building a Portfolio of
Projects that Shows
Skill Progression
CHAPTER 6
PROJECTS

2026-07-20 23:08:07,905 - INFO - > Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

2026-07-20 23:08:07,905 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:08:07,905 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: 3b9166f3-dfbb-48eb-8c71-ae56958763dd.
> Parent node text: PAGE 21
Building a Portfolio of
Projects that Shows
Skill Progression
CHAPTER 6
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:08:08,693 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:08:28,116 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:08:28,123 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:08:48,757 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:09:19,071 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:09:38,620 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 427dcb81-2e10-424d-b5c2-c1972362e7c7.
> Parent node text: PAGE 25
Finding a job has a few predictable steps that include selecting the companies to which y...

2026-07-20 23:09:38,621 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 31158589-a647-46bd-bacf-a0ffdaabb696.
> Parent node text: PAGE 26
If you’re considering a role switch, a startup can be an easier place to do it than a big...

2026-07-20 23:09:38,621 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

2026-07-20 23:09:38,621 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

2026-07-20 23:09:38,621 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 23:09:38,621 - INFO - > Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

2026-07-20 23:09:38,622 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:09:38,622 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 23:09:38,622 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

2026-07-20 23:09:38,622 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:09:38,622 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

> Merging 1 nodes into parent node.
> Parent node id: 427dcb81-2e10-424d-b5c2-c1972362e7c7.
> Parent node text: PAGE 25
Finding a job has a few predictable steps that include selecting the companies to which y...

> Merging 1 nodes into parent node.
> Parent node id: 31158589-a647-46bd-bacf-a0ffdaabb696.
> Parent node text: PAGE 26
If you’re considering a role switch, a startup can be an easier place to do it than a big...

> Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

> Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:09:39,325 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:10:06,937 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:10:06,945 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:10:28,723 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:11:02,535 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:11:25,019 - INFO - > Merging 1 nodes into parent node.
> Parent node id: e8b5b912-693c-47b4-9259-f537271f7ed2.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

2026-07-20 23:11:25,020 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 5862063c-987b-4078-bcd4-4bcbeecaa84c.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

2026-07-20 23:11:25,020 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 20e5214b-501a-4b11-aa92-d4b4d605f106.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

2026-07-20 23:11:25,020 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:11:25,020 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

2026-07-20 23:11:25,021 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

2026-07-20 23:11:25,021 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

2026-07-20 23:11:25,021 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

2026-07-20 23:11:25,021 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:11:25,021 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 1267eff1-6091-4291-84d1-44e633e33041.
> Parent node text: PAGE 8
Learning Technical
Skills for a Promising
AI Career
CHAPTER 2
LEARNING

2026-07-20 23:11:25,021 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

2026-07-20 23:11:25,021 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: e8b5b912-693c-47b4-9259-f537271f7ed2.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

> Merging 1 nodes into parent node.
> Parent node id: 5862063c-987b-4078-bcd4-4bcbeecaa84c.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

> Merging 1 nodes into parent node.
> Parent node id: 20e5214b-501a-4b11-aa92-d4b4d605f106.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 1 nodes into parent node.
> Parent node id: c4a64af6-4606-4c65-a729-5dc4847795f6.
> Parent node text: PAGE 30
Finding someone to interview isn’t always easy, but many people who are in senior positio...

> Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

> Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 1267eff1-6091-4291-84d1-44e633e33041.
> Parent node text: PAGE 8
Learning Technical
Skills for a Promising
AI Career
CHAPTER 2
LEARNING

> Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:11:25,824 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:11:35,623 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:11:35,632 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:11:50,197 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:12:14,413 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:12:24,271 - INFO - > Merging 1 nodes into parent node.
> Parent node id: be91d620-bed1-46e9-a783-ecb686abb888.
> Parent node text: PAGE 40
Make Every Day Count
Final Thoughts
Every year on my birthday, I get to thinking about th...

2026-07-20 23:12:24,271 - INFO - > Merging 1 nodes into parent node.
> Parent node id: a3d9829b-ab51-4963-8911-25dd6d0421ea.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

2026-07-20 23:12:24,271 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 037d6910-75d4-4bca-be46-5c7e1e313ad5.
> Parent node text: PAGE 27
There’s a lot we don’t know about the future: When will we cure Alzheimer’s disease? Who ...

2026-07-20 23:12:24,272 - INFO - > Merging 2 nodes into parent node.
> Parent node id: 26d9d53a-9bf4-4293-bc6f-cb8dc9a7e993.
> Parent node text: PAGE 20
Working on projects requires making tough choices about what to build and how to go
abou...

2026-07-20 23:12:24,272 - INFO - > Merging 1 nodes into parent node.
> Parent node id: b152f8e3-18ae-4b1e-974c-7398fdabf3e9.
> Parent node text: PAGE 28
Using Informational
Interviews to Find
the Right Job
CHAPTER 8
JOBS

2026-07-20 23:12:24,272 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

2026-07-20 23:12:24,272 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

2026-07-20 23:12:24,272 - INFO - > Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

2026-07-20 23:12:24,272 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 28c734a7-6ca8-4a30-9b43-41d268e028de.
> Parent node text: PAGE 2
"AI is the new
electricity. It will
transform and improve
all areas of human life."
And...

2026-07-20 23:12:24,272 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

> Merging 1 nodes into parent node.
> Parent node id: be91d620-bed1-46e9-a783-ecb686abb888.
> Parent node text: PAGE 40
Make Every Day Count
Final Thoughts
Every year on my birthday, I get to thinking about th...

> Merging 1 nodes into parent node.
> Parent node id: a3d9829b-ab51-4963-8911-25dd6d0421ea.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

> Merging 1 nodes into parent node.
> Parent node id: 037d6910-75d4-4bca-be46-5c7e1e313ad5.
> Parent node text: PAGE 27
There’s a lot we don’t know about the future: When will we cure Alzheimer’s disease? Who ...

> Merging 2 nodes into parent node.
> Parent node id: 26d9d53a-9bf4-4293-bc6f-cb8dc9a7e993.
> Parent node text: PAGE 20
Working on projects requires making tough choices about what to build and how to go
abou...

> Merging 1 nodes into parent node.
> Parent node id: b152f8e3-18ae-4b1e-974c-7398fdabf3e9.
> Parent node text: PAGE 28
Using Informational
Interviews to Find
the Right Job
CHAPTER 8
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

> Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

> Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

> Merging 1 nodes into parent node.
> Parent node id: 28c734a7-6ca8-4a30-9b43-41d268e028de.
> Parent node text: PAGE 2
"AI is the new
electricity. It will
transform and improve
all areas of human life."
And...

> Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:12:24,961 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:12:48,128 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:12:48,134 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:13:03,368 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:13:28,222 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:13:38,646 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

2026-07-20 23:13:38,646 - INFO - > Merging 2 nodes into parent node.
> Parent node id: 0172cff2-2e17-4235-8df9-0af3a2da9c34.
> Parent node text: PAGE 9
In the previous chapter, I introduced three key steps for building a career in AI: learnin...

2026-07-20 23:13:38,647 - INFO - > Merging 1 nodes into parent node.
> Parent node id: e8b5b912-693c-47b4-9259-f537271f7ed2.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

2026-07-20 23:13:38,647 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

2026-07-20 23:13:38,647 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

2026-07-20 23:13:38,647 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d9eb88e4-8c7a-45dc-8e60-692a9551a539.
> Parent node text: PAGE 10
This is a lot to learn!
Even after you master everything on this list, I hope you’ll keep...

2026-07-20 23:13:38,647 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:13:38,647 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 23:13:38,648 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:13:38,648 - INFO - > Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

2026-07-20 23:13:38,648 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

> Merging 2 nodes into parent node.
> Parent node id: 0172cff2-2e17-4235-8df9-0af3a2da9c34.
> Parent node text: PAGE 9
In the previous chapter, I introduced three key steps for building a career in AI: learnin...

> Merging 1 nodes into parent node.
> Parent node id: e8b5b912-693c-47b4-9259-f537271f7ed2.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

> Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

> Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

> Merging 1 nodes into parent node.
> Parent node id: d9eb88e4-8c7a-45dc-8e60-692a9551a539.
> Parent node text: PAGE 10
This is a lot to learn!
Even after you master everything on this list, I hope you’ll keep...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

> Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:13:39,334 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:13:53,000 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:13:53,007 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:14:07,671 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:14:38,755 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:14:56,784 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

2026-07-20 23:14:56,784 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:14:56,784 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6b037458-f68b-45c9-95e0-c596d0b57ad6.
> Parent node text: PAGE 14
Scoping Successful
AI Projects
CHAPTER 4
PROJECTS

2026-07-20 23:14:56,785 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

2026-07-20 23:14:56,785 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 23:14:56,785 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

2026-07-20 23:14:56,785 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

2026-07-20 23:14:56,785 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:14:56,785 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 23:14:56,786 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 3b9166f3-dfbb-48eb-8c71-ae56958763dd.
> Parent node text: PAGE 21
Building a Portfolio of
Projects that Shows
Skill Progression
CHAPTER 6
PROJECTS

2026-07-20 23:14:56,786 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

2026-07-20 23:14:56,786 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

> Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 6b037458-f68b-45c9-95e0-c596d0b57ad6.
> Parent node text: PAGE 14
Scoping Successful
AI Projects
CHAPTER 4
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

> Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: 3b9166f3-dfbb-48eb-8c71-ae56958763dd.
> Parent node text: PAGE 21
Building a Portfolio of
Projects that Shows
Skill Progression
CHAPTER 6
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

> Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:14:57,490 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:15:24,557 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:15:24,564 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:15:41,745 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:16:32,333 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:16:52,984 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:16:52,985 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:16:52,985 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 23:16:52,985 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

2026-07-20 23:16:52,985 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 23:16:52,985 - INFO - > Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

2026-07-20 23:16:52,985 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

2026-07-20 23:16:52,986 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

2026-07-20 23:16:52,986 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

2026-07-20 23:16:52,986 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 23:16:52,986 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

2026-07-20 23:16:52,986 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

> Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:16:53,763 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:17:25,571 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:17:25,583 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:17:40,877 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:18:16,479 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:18:47,879 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

2026-07-20 23:18:47,879 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

2026-07-20 23:18:47,879 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:18:47,880 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 23:18:47,880 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

2026-07-20 23:18:47,880 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 23:18:47,880 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:18:47,880 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

2026-07-20 23:18:47,880 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6b037458-f68b-45c9-95e0-c596d0b57ad6.
> Parent node text: PAGE 14
Scoping Successful
AI Projects
CHAPTER 4
PROJECTS

2026-07-20 23:18:47,880 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

> Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: f5dbc2a3-7a7c-462b-837a-b4d742d416f2.
> Parent node text: PAGE 19
Develop a side hustle. Even if you have a full-time job, a fun project that may or may no...

> Merging 1 nodes into parent node.
> Parent node id: 6b037458-f68b-45c9-95e0-c596d0b57ad6.
> Parent node text: PAGE 14
Scoping Successful
AI Projects
CHAPTER 4
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:18:48,579 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:18:58,922 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:18:58,928 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:19:13,032 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:19:54,625 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:20:07,319 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

2026-07-20 23:20:07,319 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:20:07,319 - INFO - > Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

2026-07-20 23:20:07,320 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

2026-07-20 23:20:07,320 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:20:07,320 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 5862063c-987b-4078-bcd4-4bcbeecaa84c.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

2026-07-20 23:20:07,320 - INFO - > Merging 1 nodes into parent node.
> Parent node id: e8b5b912-693c-47b4-9259-f537271f7ed2.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

2026-07-20 23:20:07,320 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 1267eff1-6091-4291-84d1-44e633e33041.
> Parent node text: PAGE 8
Learning Technical
Skills for a Promising
AI Career
CHAPTER 2
LEARNING

2026-07-20 23:20:07,320 - INFO - > Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

2026-07-20 23:20:07,320 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 28c734a7-6ca8-4a30-9b43-41d268e028de.
> Parent node text: PAGE 2
"AI is the new
electricity. It will
transform and improve
all areas of human life."
And...

> Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

> Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 5862063c-987b-4078-bcd4-4bcbeecaa84c.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

> Merging 1 nodes into parent node.
> Parent node id: e8b5b912-693c-47b4-9259-f537271f7ed2.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

> Merging 1 nodes into parent node.
> Parent node id: 1267eff1-6091-4291-84d1-44e633e33041.
> Parent node text: PAGE 8
Learning Technical
Skills for a Promising
AI Career
CHAPTER 2
LEARNING

> Merging 1 nodes into parent node.
> Parent node id: f44f51b8-18ea-474f-b1fa-728ca132b0c6.
> Parent node text: PAGE 24
A Simple Framework
for Starting Your AI
Job Search
CHAPTER 7
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 28c734a7-6ca8-4a30-9b43-41d268e028de.
> Parent node text: PAGE 2
"AI is the new
electricity. It will
transform and improve
all areas of human life."
And...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:20:07,989 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:20:29,552 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:20:29,558 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:20:42,655 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:21:10,306 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:21:28,965 - INFO - > Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

2026-07-20 23:21:28,966 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

2026-07-20 23:21:28,966 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:21:28,967 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

2026-07-20 23:21:28,967 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 23:21:28,967 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:21:28,967 - INFO - > Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

2026-07-20 23:21:28,967 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

2026-07-20 23:21:28,967 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 8108c9c3-5c36-451c-b552-a9e329996ab6.
> Parent node text: PAGE 34
Keys to Building a
Career in AI
CHAPTER 10
JOBS

2026-07-20 23:21:28,968 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

2026-07-20 23:21:28,968 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

> Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

> Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 1 nodes into parent node.
> Parent node id: 8108c9c3-5c36-451c-b552-a9e329996ab6.
> Parent node text: PAGE 34
Keys to Building a
Career in AI
CHAPTER 10
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 5617b66c-9b07-4079-a16d-084540d331ac.
> Parent node text: PAGE 17
Finding Projects that
Complement Your
Career Goals
CHAPTER 5
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:21:29,674 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:21:46,103 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:21:46,110 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:22:02,560 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:22:26,615 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:22:42,378 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:22:42,379 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

2026-07-20 23:22:42,379 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

2026-07-20 23:22:42,380 - INFO - > Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

2026-07-20 23:22:42,380 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 5862063c-987b-4078-bcd4-4bcbeecaa84c.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

2026-07-20 23:22:42,380 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

2026-07-20 23:22:42,380 - INFO - > Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

2026-07-20 23:22:42,380 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:22:42,380 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 8108c9c3-5c36-451c-b552-a9e329996ab6.
> Parent node text: PAGE 34
Keys to Building a
Career in AI
CHAPTER 10
JOBS

2026-07-20 23:22:42,380 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

2026-07-20 23:22:42,381 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

> Merging 1 nodes into parent node.
> Parent node id: 5862063c-987b-4078-bcd4-4bcbeecaa84c.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

> Merging 1 nodes into parent node.
> Parent node id: 90c65411-f05a-4252-8da6-9dc8d3c609be.
> Parent node text: PAGE 5
Three Steps to
Career Growth
CHAPTER 1

> Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 8108c9c3-5c36-451c-b552-a9e329996ab6.
> Parent node text: PAGE 34
Keys to Building a
Career in AI
CHAPTER 10
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:22:43,056 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:22:54,262 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:22:54,268 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:23:08,400 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:23:33,658 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:23:52,138 - INFO - > Merging 2 nodes into parent node.
> Parent node id: 0172cff2-2e17-4235-8df9-0af3a2da9c34.
> Parent node text: PAGE 9
In the previous chapter, I introduced three key steps for building a career in AI: learnin...

2026-07-20 23:23:52,138 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

2026-07-20 23:23:52,138 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d9eb88e4-8c7a-45dc-8e60-692a9551a539.
> Parent node text: PAGE 10
This is a lot to learn!
Even after you master everything on this list, I hope you’ll keep...

2026-07-20 23:23:52,139 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 23:23:52,139 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

2026-07-20 23:23:52,139 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

2026-07-20 23:23:52,139 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:23:52,139 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

2026-07-20 23:23:52,139 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:23:52,139 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 23:23:52,140 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 2 nodes into parent node.
> Parent node id: 0172cff2-2e17-4235-8df9-0af3a2da9c34.
> Parent node text: PAGE 9
In the previous chapter, I introduced three key steps for building a career in AI: learnin...

> Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

> Merging 1 nodes into parent node.
> Parent node id: d9eb88e4-8c7a-45dc-8e60-692a9551a539.
> Parent node text: PAGE 10
This is a lot to learn!
Even after you master everything on this list, I hope you’ll keep...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

> Merging 1 nodes into parent node.
> Parent node id: 7e7d6679-526c-4ec1-95b7-1c432303a17c.
> Parent node text: PAGE 22
Over the course of a career, you’re likely to work on projects in succession, each growin...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 17af32d0-072b-4789-a1f8-85c56906cc21.
> Parent node text: PAGE 29
If you’re preparing to switch roles (say, taking a job as a machine learning engineer for...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:23:52,773 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:24:26,113 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:24:26,129 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:24:54,753 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:25:34,575 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:25:53,753 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

2026-07-20 23:25:53,754 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:25:53,754 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

2026-07-20 23:25:53,755 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

2026-07-20 23:25:53,755 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

2026-07-20 23:25:53,755 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:25:53,755 - INFO - > Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

2026-07-20 23:25:53,756 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

2026-07-20 23:25:53,756 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 1267eff1-6091-4291-84d1-44e633e33041.
> Parent node text: PAGE 8
Learning Technical
Skills for a Promising
AI Career
CHAPTER 2
LEARNING

2026-07-20 23:25:53,756 - INFO - > Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

2026-07-20 23:25:53,757 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6b037458-f68b-45c9-95e0-c596d0b57ad6.
> Parent node text: PAGE 14
Scoping Successful
AI Projects
CHAPTER 4
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 371fe0e6-e45f-47da-adc9-b327766f62e7.
> Parent node text: PAGE 15
One of the most important skills of an AI architect is the ability to identify ideas that...

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 1 nodes into parent node.
> Parent node id: 7c3e4bd4-d6c1-467d-907c-813a15b32ab3.
> Parent node text: PAGE 16
Determine milestones. Once you’ve deemed a project sufficiently
valuable, the next step ...

> Merging 1 nodes into parent node.
> Parent node id: 601f8e9c-a781-4370-9de7-93259f244f2f.
> Parent node text: PAGE 23
Each project is only one step on a longer journey, hopefully one that has a positive impa...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: b96be360-74a5-4477-b485-a748d63675ce.
> Parent node text: PAGE 12
Should You
Learn Math to
Get a Job in AI?
CHAPTER 3
LEARNING

> Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

> Merging 1 nodes into parent node.
> Parent node id: 1267eff1-6091-4291-84d1-44e633e33041.
> Parent node text: PAGE 8
Learning Technical
Skills for a Promising
AI Career
CHAPTER 2
LEARNING

> Merging 1 nodes into parent node.
> Parent node id: cd9742f6-fb52-4259-8f29-92c4671aa024.
> Parent node text: PAGE 6
The rapid rise of AI has led to a rapid rise in AI jobs, and many people are building exci...

> Merging 1 nodes into parent node.
> Parent node id: 6b037458-f68b-45c9-95e0-c596d0b57ad6.
> Parent node text: PAGE 14
Scoping Successful
AI Projects
CHAPTER 4
PROJECTS

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:25:54,427 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:26:21,766 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:26:21,772 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:26:40,340 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:27:15,649 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:27:37,128 - INFO - > Merging 1 nodes into parent node.
> Parent node id: e8b5b912-693c-47b4-9259-f537271f7ed2.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

2026-07-20 23:27:37,128 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 20e5214b-501a-4b11-aa92-d4b4d605f106.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

2026-07-20 23:27:37,128 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

2026-07-20 23:27:37,128 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 5862063c-987b-4078-bcd4-4bcbeecaa84c.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

2026-07-20 23:27:37,129 - INFO - > Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

2026-07-20 23:27:37,129 - INFO - > Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

2026-07-20 23:27:37,129 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

2026-07-20 23:27:37,129 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

2026-07-20 23:27:37,129 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

2026-07-20 23:27:37,129 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

2026-07-20 23:27:37,129 - INFO - > Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

2026-07-20 23:27:37,130 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 28c734a7-6ca8-4a30-9b43-41d268e028de.
> Parent node text: PAGE 2
"AI is the new
electricity. It will
transform and improve
all areas of human life."
And...

> Merging 1 nodes into parent node.
> Parent node id: e8b5b912-693c-47b4-9259-f537271f7ed2.
> Parent node text: PAGE 38
Before we dive into the final chapter of this book, I’d like to address the serious matte...

> Merging 1 nodes into parent node.
> Parent node id: 20e5214b-501a-4b11-aa92-d4b4d605f106.
> Parent node text: PAGE 37
Overcoming Imposter
Syndrome
CHAPTER 11

> Merging 1 nodes into parent node.
> Parent node id: 14509e8d-55e1-495d-bd29-e65aed029d01.
> Parent node text: PAGE 3
Table of
Contents
Introduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to ...

> Merging 1 nodes into parent node.
> Parent node id: 5862063c-987b-4078-bcd4-4bcbeecaa84c.
> Parent node text: PAGE 39
My three-year-old daughter (who can barely count to 12) regularly tries to teach things t...

> Merging 1 nodes into parent node.
> Parent node id: c03d8c21-1388-44f0-a8ab-658dcaf3a378.
> Parent node text: PAGE 35
Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more compl...

> Merging 1 nodes into parent node.
> Parent node id: af4e8832-396d-4287-a2af-ccdd1182332a.
> Parent node text: PAGE 7
These phases apply in a wide
range of professions, but AI
involves unique elements.
For ...

> Merging 1 nodes into parent node.
> Parent node id: 964d0e40-0411-4fbc-b334-4c880a9f0f73.
> Parent node text: PAGE 4
Coding AI Is the New Literacy
Today we take it for granted that many people know how to re...

> Merging 1 nodes into parent node.
> Parent node id: 97869b6c-ccc1-4184-b070-656a041d8ef8.
> Parent node text: PAGE 36
Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
o...

> Merging 1 nodes into parent node.
> Parent node id: 678bfd4d-d03f-48e3-bc23-fb443f4b285d.
> Parent node text: PAGE 33
Choose who to work with. It’s tempting to take a position because of the projects you’ll ...

> Merging 1 nodes into parent node.
> Parent node id: 6c4d457b-7ccb-4b4b-b4f4-27b520a5ac3e.
> Parent node text: PAGE 13
Should you Learn Math to Get a Job in AI? CHAPTER 3
Is math a foundational skill for AI? ...

> Merging 1 nodes into parent node.
> Parent node id: d88d0cbf-5bf1-4030-b783-74c54af2fd16.
> Parent node text: PAGE 18
It goes without saying that we should only work on projects that are responsible, ethical...

> Merging 1 nodes into parent node.
> Parent node id: 28c734a7-6ca8-4a30-9b43-41d268e028de.
> Parent node text: PAGE 2
"AI is the new
electricity. It will
transform and improve
all areas of human life."
And...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-20 23:27:37,839 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:27:48,652 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-20 23:27:48,657 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:28:03,594 - INFO - AFC is enabled with max remote calls: 10.
2026-07-20 23:28:32,090 - INFO - AFC is enabled with max remote calls: 10.

,app_id,question,answer,answer_relevancy,context_relevancy,groundedness
0,app_0,"In the context of job switching, what advantag...",Working in a startup can make switching roles ...,1.0,1.0,1.0
1,app_0,Explain the scenario planning exercise mention...,"During the Covid-19 pandemic, a scenario plann...",1.0,1.0,1.0
2,app_0,In the context of project selection and execut...,"The ""Ready, Aim, Fire"" and ""Ready, Fire, Aim"" ...",1.0,1.0,1.0
3,app_0,Discuss the importance of working on projects ...,Working on projects that complement career goa...,1.0,1.0,1.0
4,app_0,"According to the text, what are some of the ke...",Key areas of mathematics relevant to machine l...,1.0,1.0,1.0

In [30]:
summarize_eval_df(records_app0)

  app_id  answer_relevancy  context_relevancy  groundedness
0  app_0               1.0           0.984375           1.0

In [31]:
print("Auto-merging app_0 evaluation complete.")

Auto-merging app_0 evaluation complete.

In [32]:
pass  # reserved

In [33]:
pass  # reserved

### Three layers

In [38]:
auto_merging_index_1 = build_automerging_index(
    documents,
    llm=GoogleGenAI(
        model="gemma-4-31b-it",
        api_key=utils.get_google_api_key(),
        temperature=0.1,
    ),
    embed_model="local:BAAI/bge-small-en-v1.5",
    save_dir="merging_index_1",
    chunk_sizes=[2048,512,128],
)

2026-07-21 08:08:51,584 - INFO - HTTP Request: GET https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it "HTTP/1.1 200 OK"
2026-07-21 08:08:51,976 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:51,997 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-21 08:08:52,306 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:52,327 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-21 08:08:52,331 - INFO - Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-07-21 08:08:52,608 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:52,628 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-07-21 08:08:53,023 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:53,045 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
2026-07-21 08:08:53,325 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:53,347 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
2026-07-21 08:08:53,626 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:53,648 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-07-21 08:08:53,982 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-21 08:08:54,269 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:54,287 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

2026-07-21 08:08:54,661 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-21 08:08:54,957 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-21 08:08:55,480 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-21 08:08:55,891 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-21 08:08:56,156 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:56,178 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-21 08:08:56,455 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:56,477 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-21 08:08:56,759 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:56,784 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
2026-07-21 08:08:57,220 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:57,241 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-21 08:08:57,538 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-21 08:08:57,820 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-21 08:08:58,179 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 08:08:58,200 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-07-21 08:08:58,486 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-07-21 08:08:58,828 - INFO - Loaded 1 prompt with these keys: ['query']
2026-07-21 08:08:58,944 - INFO - Loading all indices.

In [41]:
auto_merging_engine_1 = get_automerging_query_engine(
    auto_merging_index_1,
    similarity_top_k=12,
    rerank_top_n=6,
)

2026-07-21 09:07:57,214 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/modules.json "HTTP/1.1 404 Not Found"
2026-07-21 09:07:57,217 - INFO - No modules.json found for BAAI/bge-reranker-base, initializing a new CrossEncoder model.
2026-07-21 09:07:57,483 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"
2026-07-21 09:07:57,782 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 09:07:57,822 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-21 09:07:58,169 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-21 09:07:58,439 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 09:07:58,479 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

2026-07-21 09:07:58,852 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-07-21 09:07:59,127 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-21 09:07:59,409 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-21 09:07:59,743 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-07-21 09:08:00,011 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 09:08:00,052 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-21 09:08:00,330 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 09:08:00,372 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-21 09:08:00,666 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 09:08:00,706 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/config.json "HTTP/1.1 200 OK"
2026-07-21 09:08:00,997 - INFO - HTTP Request: HEAD https://huggingface.co/BAAI/bge-reranker-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-21 09:08:01,038 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-reranker-base/2cfc18c9415c912f9d8155881c133215df768a70/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-21 09:08:01,317 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-21 09:08:01,597 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-21 09:08:03,967 - INFO - HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-reranker-base "HTTP/1.1 200 OK"

In [42]:
records_app1 = evaluate_query_engine(
    auto_merging_engine_1,
    eval_questions,
    app_id="app_1",
    llm=eval_llm,
)
records_app1.head()

2026-07-21 09:08:08,363 - INFO - > Merging 4 nodes into parent node.
> Parent node id: bff386ce-76c9-4064-be02-3d3875783eda.
> Parent node text: PAGE 26
If you’re considering a role switch, a startup can be an easier place to do it than a big...

2026-07-21 09:08:08,363 - INFO - > Merging 4 nodes into parent node.
> Parent node id: bf05f3d0-36c4-4f1a-9e43-a85162047439.
> Parent node text: PAGE 25
Finding a job has a few predictable steps that include selecting the companies to which y...

2026-07-21 09:08:08,363 - INFO - > Merging 1 nodes into parent node.
> Parent node id: 28456032-dea5-4b25-849d-cc348f3b95f1.
> Parent node text: PAGE 26
If you’re considering a role switch, a startup can be an easier place to do it than a big...

2026-07-21 09:08:08,364 - INFO - > Merging 1 nodes into parent node.
> Parent node id: decfd9f4-d55e-428e-8829-7260bcb7e7bb.
> Parent node text: PAGE 25
Finding a job has a few predictable steps that include selecting the companies to which y...

> Merging 4 nodes into parent node.
> Parent node id: bff386ce-76c9-4064-be02-3d3875783eda.
> Parent node text: PAGE 26
If you’re considering a role switch, a startup can be an easier place to do it than a big...

> Merging 4 nodes into parent node.
> Parent node id: bf05f3d0-36c4-4f1a-9e43-a85162047439.
> Parent node text: PAGE 25
Finding a job has a few predictable steps that include selecting the companies to which y...

> Merging 1 nodes into parent node.
> Parent node id: 28456032-dea5-4b25-849d-cc348f3b95f1.
> Parent node text: PAGE 26
If you’re considering a role switch, a startup can be an easier place to do it than a big...

> Merging 1 nodes into parent node.
> Parent node id: decfd9f4-d55e-428e-8829-7260bcb7e7bb.
> Parent node text: PAGE 25
Finding a job has a few predictable steps that include selecting the companies to which y...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-07-21 09:08:09,933 - ERROR - Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x1076c1b40> is already entered
2026-07-21 09:08:09,945 - INFO - AFC is enabled with max remote calls: 10.
2026-07-21 09:08:23,510 - INFO - HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemma-4-31b-it:generateContent "HTTP/1.1 200 OK"
2026-07-21 09:08:23,517 - INFO - AFC is enabled with max remote calls: 10.
2026-07-21 09:08:23,569 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1121' coro=<_async_in_context.<locals>.run_in_context() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task pending name='Task-1125' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>
2026-07-21 09:08:23,570 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1125' coro=<Kernel.shell_main() running at /Users/worawatlawanont/Projects/sut-ai-sw-dev/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597> cb=[Task.__wakeup()]>

RuntimeError: Detected nested async. Please use nest_asyncio.apply() to allow nested event loops.Or, use async entry methods like `aquery()`, `aretriever`, `achat`, etc.

In [ ]:
summarize_eval_df(records_app1)

In [ ]:
import pandas as pd

comparison = pd.concat(
    [summarize_eval_df(records_app0), summarize_eval_df(records_app1)],
    ignore_index=True,
)
comparison

In [ ]:
print("Auto-merging comparison complete.")